{var cajaBuildVersion='5470m',ArrayLike,JSON,Proxy,Q,WeakMap,___,cajaVM,json_sans_eval,loadModuleMaker,prepareModuleFromText___,safeJSON;typeof
window!=='undefined'&&(window['cajaBuildVersion']=cajaBuildVersion),typeof Date.prototype.toJSON!=='function'&&(Date.prototype.toJSON=function(key){function
f(n){return n<10?'0'+n:n}return isFinite(this.valueOf())?this.getUTCFullYear()+'-'+f(this.getUTCMonth()+1)+'-'+f(this.getUTCDate())+'T'+f(this.getUTCHours())+':'+f(this.getUTCMinutes())+':'+f(this.getUTCSeconds())+'Z':null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(key){return this.valueOf()}),json_sans_eval=(function(){var
hop=Object.hasOwnProperty,cx=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,meta={'\b':'\\b','\t':'\\t','\n':'\\n','\f':'\\f','\r':'\\r','\"':'\\\"','\\':'\\\\'},EMPTY_STRING,SLASH,completeToken,escapeSequence,escapes,gap,indent,number,oneChar,rep,significantToken,string;function
quote(string){return escapable.lastIndex=0,escapable.test(string)?'\"'+string.replace(escapable,function(a){var
c=meta[a];return typeof c==='string'?c:'\\u'+('0000'+a.charCodeAt(0).toString(16)).slice(-4)})+'\"':'\"'+string+'\"'}function
str(key,holder){var mind=gap,value=holder[key],i,k,length,partial,v;value&&typeof
value==='object'&&typeof value.toJSON==='function'&&(value=value.toJSON(key)),typeof
rep==='function'&&(value=rep.call(holder,key,value));switch(typeof value){case'string':return quote(value);case'number':return isFinite(value)?String(value):'null';case'boolean':case'null':return String(value);case'object':if(!value)return'null';gap+=indent,partial=[];if(Object.prototype.toString.apply(value)==='[object Array]'){length=value.length;for(i=0;i<length;i+=1)partial[i]=str(i,value)||'null';return v=partial.length===0?'[]':gap?'[\n'+gap+partial.join(',\n'+gap)+'\n'+mind+']':'['+partial.join(',')+']',gap=mind,v}if(rep&&typeof
rep==='object'){length=rep.length;for(i=0;i<length;i+=1)k=rep[i],typeof k==='string'&&(v=str(k,value),v&&partial.push(quote(k)+(gap?': ':':')+v))}else
for(k in value)hop.call(value,k)&&(v=str(k,value),v&&partial.push(quote(k)+(gap?': ':':')+v));return v=partial.length===0?'{}':gap?'{\n'+gap+partial.join(',\n'+gap)+'\n'+mind+'}':'{'+partial.join(',')+'}',gap=mind,v}}function
stringify(value,replacer,space){var i;gap='',indent='';if(typeof space==='number')for(i=0;i<space;i+=1)indent+=' ';else
if(typeof space==='string')indent=space;rep=replacer;if(replacer&&typeof replacer!=='function'&&(typeof
replacer!=='object'||typeof replacer.length!=='number'))throw new Error('json_sans_eval.stringify');return str('',{'':value})}number='(?:-?\\b(?:0|[1-9][0-9]*)(?:\\.[0-9]+)?(?:[eE][+-]?[0-9]+)?\\b)',oneChar='(?:[^\\0-\\x08\\x0a-\\x1f\"\\\\]|\\\\(?:[\"/\\\\bfnrt]|u[0-9A-Fa-f]{4}))',string='(?:\"'+oneChar+'*\")',significantToken=new
RegExp(('(?:false|true|null|[\\{\\}\\[\\]]|'+number+'|'+string+')'),'g'),escapeSequence=new
RegExp('\\\\(?:([^u])|u(.{4}))','g'),escapes={'\"':'\"','/':'/','\\':'\\','b':'\b','f':'\f','n':'\n','r':'\r','t':'\t'};function
unescapeOne(_,ch,hex){return ch?escapes[ch]:String.fromCharCode(parseInt(hex,16))}EMPTY_STRING=new
String(''),SLASH='\\',completeToken=new RegExp(('(?:false|true|null|[ \t\r\n]+|[\\{\\}\\[\\],:]|'+number+'|'+string+'|.)'),'g');function
blank(arr,s,e){while(--e>=s)arr[e]=''}function checkSyntax(text,keyFilter){var toks=(''+text).match(completeToken),i=0,n=toks.length;checkArray();if(i<n)throw new
Error(('Trailing tokens '+toks.slice(i-1).join('')));return toks.join('');function
checkArray(){var t;while(i<n){t=toks[i++];switch(t){case']':return;case'[':checkArray();break;case'{':checkObject()}}}function
checkObject(){var state=0,len,t;while(i<n){t=toks[i++];switch(t.charCodeAt(0)){case
9:case 10:case 13:case 32:continue;case 34:len=t.length;if(len===1)throw new Error(t);if(state===0){if(keyFilter&&!keyFilter(t.substring(1,len-1).replace(escapeSequence,unescapeOne)))throw new
Error(t)}else if(state!==2)throw new Error(t);break;case 39:throw new Error(t);case
44:if(state!==3)throw new Error(t);state=0;continue;case 58:if(state!==1)throw new
Error(t);break;case 91:if(state!==2)throw new Error(t);checkArray();break;case 123:if(state!==2)throw new
Error(t);checkObject();break;case 125:return;default:if(state!==2)throw new Error(t)}++state}}}function
parse(json,opt_reviver){var toks=json.match(significantToken),tok=toks[0],cont,i,key,n,result,stack,walk;if('{'===tok)result={};else
if('['===tok)result=[];else throw new Error(tok);key=void 0,stack=[result];for(i=1,n=toks.length;i<n;++i){tok=toks[i];switch(tok.charCodeAt(0)){default:cont=stack[0],cont[key||cont.length]=+tok,key=void
0;break;case 34:tok=tok.substring(1,tok.length-1),tok.indexOf(SLASH)!==-1&&(tok=tok.replace(escapeSequence,unescapeOne)),cont=stack[0];if(!key)if(cont
instanceof Array)key=cont.length;else{key=tok||EMPTY_STRING;break}cont[key]=tok,key=void
0;break;case 91:cont=stack[0],stack.unshift(cont[key||cont.length]=[]),key=void 0;break;case
93:stack.shift();break;case 102:cont=stack[0],cont[key||cont.length]=false,key=void
0;break;case 110:cont=stack[0],cont[key||cont.length]=null,key=void 0;break;case
116:cont=stack[0],cont[key||cont.length]=true,key=void 0;break;case 123:cont=stack[0],stack.unshift(cont[key||cont.length]={}),key=void
0;break;case 125:stack.shift()}}if(stack.length)throw new Error;return opt_reviver&&(walk=function(holder,key){var
value=holder[key],i,k,toDelete,v;if(value&&typeof value==='object'){toDelete=null;for(k
in value)hop.call(value,k)&&value!==holder&&(v=walk(value,k),v!==void 0?(value[k]=v):(toDelete||(toDelete=[]),toDelete.push(k)));if(toDelete)for(i=toDelete.length;--i>=0;)delete
value[toDelete[i]]}return opt_reviver.call(holder,key,value)},result=walk({'':result},'')),result}return{'checkSyntax':checkSyntax,'parse':parse,'stringify':stringify}})(),typeof
JSON==='undefined'&&(JSON={}),typeof JSON.stringify!=='function'&&(JSON.stringify=json_sans_eval.stringify),typeof
JSON.parse!=='function'&&(JSON.parse=json_sans_eval.parse),(function(global){var
Array=global.Array,Boolean=global.Boolean,Date=global.Date,Function=global.Function,Number=global.Number,Object=global.Object,RegExp=global.RegExp,String=global.String,BASE_OBJECT_CONSTRUCTOR,CajaProxy,FakeFunction,GuardMark,GuardStamp,GuardT,HostWeakMap,MAGIC_NAME,MAGIC_NUM,MAGIC_TOKEN,NO_RESULT,USELESS,antidote,attributeDefaults,cajaVMKeys,classProp,def,defProp,defaultDerivedTraps,defended,endsWith__,endsWith_e___,endsWith_v___,fastOwnKeys,functionInstanceVoidNameGetter,goodJSON,gopd,hasOwnProperty,hostWeakMapOK,i,itemMap,lengthGetter,lengthMap,magicCount,makeArrayLike,min,myLogFunc,myNewModuleHandler,nativeProxies,numericGetters,obtainNewModule,parser,poisonArgsCallee,poisonArgsCaller,poisonFuncArgs,poisonFuncCaller,push,registeredImports,replace,sharedImports,slice,sort,startsWithNUM___,stdGetOwnPropertyDescriptor,stdGetPrototypeOf,trimBeginRegexp,trimEndRegexp,virtualizedProperties,virtualizedPropertiesFrozen;classProp=Object.prototype.toString,gopd=Object.getOwnPropertyDescriptor,defProp=Object.defineProperty,Object.prototype.baseProto___=Object.prototype,slice=Array.prototype.slice,push=Array.prototype.push,sort=Array.prototype.sort,min=Math.min,replace=String.prototype.replace,antidote=function(){return};function
deodorize(original,end){var i;if(original.__defineGetter__)for(i=end;i<0;++i)original.__defineGetter__(i,antidote)}function
isDeodorized(original,sprop){return original.__lookupGetter__?original.__lookupGetter__(sprop)===antidote:false}deodorize(Function.prototype,-6),deodorize(String.prototype,-1),deodorize(RegExp.prototype,-6),deodorize(RegExp,-6);function
notFunction(fn,opt_name){throw new TypeError(('Expected '+(opt_name?opt_name+' to be ':'')+'a function, not '+typeof
fn+': '+fn))}function notObject(obj,opt_name){throw new TypeError(('Expected '+(opt_name?opt_name+' to be ':'')+'an object, not '+typeof
obj+': '+obj))}Array.prototype.forEach||(Array.prototype.forEach=function(fun){var
dis=ToObject(this),len=dis.length>>>0,i,thisp;'function'!==typeof fun&&notFunction(fun),thisp=arguments[1];for(i=0;i<len;++i)i
in dis&&fun.call(thisp,dis[i],i,dis)}),hasOwnProperty=Object.prototype.hasOwnProperty,fastOwnKeys=Object.keys||function(o){var
keys=[],k;for(k in o)hasOwnProperty.call(o,k)&&keys.push(k);return keys},Object.prototype.freeze___=function
freeze___(){var P,i,k,keys,n;if(this.z___===this)return this;this.v___===deferredV&&this.v___('length'),keys=fastOwnKeys(this);for(k=0,n=keys.length;k<n;++k){i=keys[k];if(i.length<=5||i.substr(i.length-5)!=='_v___')continue;P=i.substr(0,i.length-5),this[P+'_c___']=false,this[P+'_gw___']=false,this[P+'_w___']=false}return this.NUM____v___!==this&&(this.NUM____v___=this,this.NUM____e___=this,this.NUM____g___=void
0,this.NUM____s___=void 0,this.NUM____av___=false),this.NUM____c___=false,this.NUM____w___=false,this.NUM____m___=false,this.NUM____gw___=false,this.ne___=this,this.z___=this,this};function
isPrototypical(obj){var constr;return typeof obj!=='object'?false:obj===null?false:(constr=obj.constructor,typeof
constr!=='function'?false:constr.prototype===obj)}BASE_OBJECT_CONSTRUCTOR={};function
directConstructor(obj){var oldConstr,proto,result;if(obj===null)return;if(obj===void
0)return;if(typeof obj!=='object')return;if(obj.hasOwnProperty('Prototype___')){proto=obj.Prototype___;if(proto===null)return;result=proto.constructor,(result.prototype!==proto||typeof
result!=='function')&&(result=directConstructor(proto))}else{if(!obj.hasOwnProperty('constructor'))result=obj.constructor;else{oldConstr=obj.constructor;if(delete
obj.constructor)result=obj.constructor,obj.constructor=oldConstr;else if(isPrototypical(obj))return log('Guessing the directConstructor of : '+obj),BASE_OBJECT_CONSTRUCTOR;else
throw new TypeError(('Discovery of direct constructors unsupported when the constructor property is not deletable: '+obj+'.constructor === '+oldConstr))}if(typeof
result!=='function'||!(obj instanceof result)){if(obj===obj.baseProto___)return;throw new
TypeError('Discovery of direct constructors for foreign begotten objects not implemented on this platform')}result.prototype.constructor===result&&(obj.Prototype___=result.prototype)}return result===result.FERAL_FRAME_OBJECT___?BASE_OBJECT_CONSTRUCTOR:result===obj.CAJA_FRAME_OBJECT___?BASE_OBJECT_CONSTRUCTOR:result}Object.prototype.CAJA_FRAME_OBJECT___=Object;function
isDefinedInCajaFrame(o){return!!o.CAJA_FRAME_OBJECT___}Object.prototype.NUM____v___=Object.prototype,Object.prototype.NUM____gw___=false,Object.prototype.NUM____w___=false,Object.prototype.NUM____m___=false,Object.prototype.NUM____c___=false,Object.prototype.NUM____e___=Object.prototype,Object.prototype.NUM____g___=void
0,Object.prototype.NUM____s___=void 0,Object.prototype.NUM____av___=false,Object.prototype.hasNumerics___=function(){return this.NUM____v___===this};function
isFrozen(obj){return obj.z___===obj}Array.prototype.length_v___=false,Array.prototype.length_gw___=false,Array.prototype.length_w___=false,Array.prototype.length_m___=false,Array.prototype.length_c___=false,Array.prototype.length_e___=false,Array.prototype.length_av___=false,Array.prototype.length_s___=markFunc(function(val){if(this.z___===this)throw new
TypeError('Cannot change the length of a frozen array.');val=ToUint32(val);if(val>=this.length)return this.length=val;if(!this.hasNumerics___()||this.NUM____c___===this)return this.length=val;throw new
TypeError('Shortening array may delete non-configurable elements.')}),Array.prototype.length_g___=markFunc(function(){return this.length});function
safeDis(dis){if(dis===null||dis===void 0)return USELESS;if(Type(dis)!=='Object')return dis;if('___'in
dis)throw new Error('Internal: toxic global!');return asFirstClass(dis)}endsWith__=/__$/,endsWith_e___=/([\s\S]*)_e___$/,endsWith_v___=/([\s\S]*)_v___$/,startsWithNUM___=/^NUM___/;function
assertValidPropertyName(P){if(endsWith__.test(P))throw new TypeError('Properties may not end in double underscore.')}function
callFault(var_args){throw new Error('Internal: toxic function encountered!')}function
getter(obj,name){return obj[name+'_g___']}function setter(obj,name){return obj[name+'_s___']}function
hasOwnAccessor(obj,name){var valueFlag=name+'_v___';return obj.hasOwnProperty(valueFlag)&&!obj[valueFlag]}function
fastpathWrite(obj,name){obj[name+'_gw___']=obj,obj[name+'_m___']=false,obj[name+'_w___']=obj}function
fastpathMethod(obj,name){obj[name+'_w___']=false,obj[name+'_m___']=true}functionInstanceVoidNameGetter=markFunc(function(){return''}),freeze(functionInstanceVoidNameGetter);function
installFunctionInstanceProps(f){var name;delete f.v___,delete f.w___,delete f.c___,delete
f.DefineOwnProperty___,name=f.name___,delete f.name___,f.prototype_v___=f,f.prototype_w___=f,f.prototype_gw___=f,f.prototype_c___=false,f.prototype_e___=false,f.prototype_g___=void
0,f.prototype_s___=void 0,f.prototype_m___=false,f.prototype_av___=false,f.length_v___=f,f.length_w___=false,f.length_gw___=false,f.length_c___=false,f.length_e___=false,f.length_g___=void
0,f.length_s___=void 0,f.length_m___=false,f.length_av___=false,f.name_v___=false,f.name_w___=false,f.name_gw___=false,f.name_c___=false,f.name_e___=false,f.name_g___=name===''?functionInstanceVoidNameGetter:markConstFunc(function(){return name}),f.name_s___=void
0,f.name_m___=false,f.name_av___=f,f.caller_v___=false,f.caller_w___=false,f.caller_gw___=false,f.caller_c___=false,f.caller_e___=false,f.caller_g___=poisonFuncCaller,f.caller_s___=void
0,f.caller_m___=false,f.caller_av___=false,f.arguments_v___=false,f.arguments_w___=false,f.arguments_gw___=false,f.arguments_c___=false,f.arguments_e___=false,f.arguments_g___=poisonFuncArgs,f.arguments_s___=void
0,f.arguments_m___=false,f.arguments_av___=false}function deferredV(name){return installFunctionInstanceProps(this),this.v___?this.v___(name):void
0}function deferredW(name,val){return installFunctionInstanceProps(this),this.w___(name,val)}function
deferredC(name){return installFunctionInstanceProps(this),this.c___(name)}function
deferredDOP(name,desc){return installFunctionInstanceProps(this),this.DefineOwnProperty___(name,desc)}function
markFunc(fn,name){var p;if(fn.ok___)return fn;isFunction(fn)||notFunction(fn);if(fn.f___!==Function.prototype.f___&&fn.f___!==fn.apply)throw new
TypeError(('The function is already tamed or not from this frame.\n'+fn.f___));return fn.f___=fn.apply,fn.ok___=true,fn.new___=fn,fn.name___=name===''||name===void
0?'':''+name,fn.v___=deferredV,fn.w___=deferredW,fn.c___=deferredC,fn.DefineOwnProperty___=deferredDOP,p=fn.prototype,p&&typeof
p==='object'&&!p.hasOwnProperty('constructor_v___')&&(p.constructor_v___=p,p.constructor_w___=p,p.constructor_gw___=p,p.constructor_c___=p,p.constructor_e___=false,p.constructor_g___=void
0,p.constructor_s___=void 0,p.constructor_m___=false,p.constructor_av___=false),fn}function
markSafeFunc(fn,name){return markFunc(fn,name),fn.i___=function(){return fn.f___(USELESS,arguments)},fn}function
markConstFunc(fn,name){return markFunc(fn,name),fn.prototype=null,freeze(fn)}function
constFunc(fn){return fn.w___('prototype',null),freeze(fn)}function hasValue(obj,name){return!!obj[name+'_v___']}function
hasOwnValue(obj,name){return obj[name+'_v___']===obj||name==='NUM___'}Object.prototype.HasOwnProperty___=function(name){return this.hasOwnProperty(name+'_v___')||name==='NUM___'};function
isWritable(obj,name){return obj[name+'_w___']===obj?true:obj[name+'_gw___']===obj?(obj[name+'_av___']!==obj&&(obj[name+'_m___']=false,obj[name+'_w___']=obj),true):name==='NUM___'&&!obj.hasNumerics___()?(obj.NUM____v___=obj,obj.NUM____gw___=obj,obj.NUM____w___=false,obj.NUM____c___=obj,obj.NUM____e___=obj,obj.NUM____g___=void
0,obj.NUM____s___=void 0,obj.NUM____m___=false,obj.NUM____av___=false,true):false}function
isEnumerable(obj,name){return!!obj[name+'_e___']}function isConfigurable(obj,name){return obj[name+'_c___']===obj||name==='NUM___'&&!obj.hasNumerics___()}function
isExtensible(obj){return Type(obj)==='Object'&&obj.ne___!==obj}function wouldExtend(obj,name){return isNumericName(name)?!obj.hasOwnProperty(name):hasOwnValue(obj,name)?false:!obj[name+'_s___']}function
isArray(obj){return classProp.call(obj)==='[object Array]'}function isFunction(obj){return classProp.call(obj)==='[object Function]'}function
isError(obj){return classProp.call(obj)==='[object Error]'}Object.prototype.e___=function(){return this};function
allKeys(obj){return obj.allKeys___()}Object.prototype.allKeys___=function(){var
result=[],i,m;for(i in this)if(isNumericName(i))result.push(i);else{if(startsWithNUM___.test(i)&&endsWith__.test(i))continue;m=i.match(endsWith_v___),m&&result.push(m[1])}return result};function
ownEnumKeys(obj){return obj.keys___()}Object.prototype.keys___=function(){var result=[],i,m;for(i
in this){if(!this.hasOwnProperty(i))continue;if(isNumericName(i))result.push(i);else{if(startsWithNUM___.test(i)&&endsWith__.test(i))continue;m=i.match(endsWith_e___),m&&this[i]&&result.push(m[1])}}return result},Object.prototype.ownKeys___=function(){var
result=[],seen={},i,k,key,keys,m,n,suffix;keys=fastOwnKeys(this);for(k=0,n=keys.length;k<n;++k)i=keys[k],typeof
i==='number'||''+ +i===i?result.push(i):5<i.length&&(suffix=i.substr(i.length-5),key=i.substr(0,i.length-5),!seen['$'+key]&&(suffix==='_v___'||suffix==='_g___'||suffix==='_s___')&&i.substr(0,6)!=='NUM___'&&(result.push(key),seen['$'+key]=1));return result};function
ownUntamedKeys(obj){var result=[],i,m;for(i in obj)obj.hasOwnProperty(i)&&(isNumericName(i)||!endsWith__.test(i))&&result.push(i);return result}function
Token(name){return name=''+name,snowWhite({'toString':markConstFunc(function tokenToString(){return name}),'throwable___':true})}function
isNumericName(n){return typeof n==='number'||''+ +n===n}function jsonParseOk(json){var
x;try{return x=json.parse('{\"a\":3}'),x.a===3}catch(e){return false}}function
jsonStringifyOk(json){var x;try{return x=json.stringify({'a':3,'b__':4},function
replacer(k,v){return/__$/.test(k)?void 0:v}),x!=='{\"a\":3}'?false:(x=json.stringify(void
0,'invalid'),x===void 0)}catch(e){return false}}goodJSON={},parser=jsonParseOk(JSON)?JSON.parse:json_sans_eval.parse,goodJSON.parse=markFunc(function(){return whitelistAll(parser.apply(this,arguments),true)}),goodJSON.stringify=markFunc(jsonStringifyOk(JSON)?JSON.stringify:json_sans_eval.stringify),safeJSON=snowWhite({'CLASS___':'JSON','parse':markFunc(function(text,opt_reviver){var
reviver=void 0;return opt_reviver&&(reviver=markFunc(function(key,value){return opt_reviver.f___(this,arguments)})),goodJSON.parse(json_sans_eval.checkSyntax(text,function(key){return!endsWith__.test(key)}),reviver)}),'stringify':markFunc(function(obj,opt_replacer,opt_space){var
replacer;switch(typeof opt_space){case'number':case'string':case'undefined':break;default:throw new
TypeError('Third arg to stringify must be a number or string')}return replacer=markFunc(opt_replacer?function(key,value){return this.HasProperty___(key)?opt_replacer.f___(this,arguments):void
0}:function(key,value){return this[key+'_g___']?this[key+'_g___'].i___():this.HasProperty___(key)||key===''?value:void
0}),goodJSON.stringify(obj,replacer,opt_space)})});function defaultLogger(str,opt_stop){}myLogFunc=markConstFunc(defaultLogger);function
getLogFunc(){return myLogFunc}markFunc(getLogFunc);function setLogFunc(newLogFunc){myLogFunc=newLogFunc}markFunc(setLogFunc);function
log(str){myLogFunc(''+str)}markFunc(log);function enforce(test,var_args){if(!test)throw new
Error((slice.call(arguments,1).join('')));return true}function enforceType(specimen,typename,opt_name){if(typeof
specimen!==typename)throw new TypeError(('Expected '+typename+', not '+typeof specimen+': '+(opt_name||specimen)));return specimen}function
enforceNat(specimen){enforceType(specimen,'number');if(specimen<0||specimen===specimen+1||Math.floor(specimen)!==specimen)throw new
TypeError(('Must be a non-negative integer: '+specimen));if(Math.floor(specimen-1)!==specimen-1)throw new
TypeError(('Integer too large: '+specimen));return specimen}function deprecate(func,badName,advice){var
warningNeeded=true;return function(){return warningNeeded&&(log('\"'+badName+'\" is deprecated.\n'+advice),warningNeeded=false),func.apply(USELESS,arguments)}}magicCount=0,MAGIC_NUM=Math.random(),MAGIC_TOKEN=Token('MAGIC_TOKEN_FOR:'+MAGIC_NUM),MAGIC_NAME='_index;'+MAGIC_NUM+';';function
newTable(opt_useKeyLifetime,opt_expectedSize){var myMagicIndexName,myValues;++magicCount,myMagicIndexName=MAGIC_NAME+magicCount+'___';function
setOnKey(key,value){var ktype=typeof key,i,list;(!key||ktype!=='function'&&ktype!=='object')&&notObject(key,'WeakMap key'),list=key[myMagicIndexName];if(!list||list[0]!==key)key[myMagicIndexName]=[key,MAGIC_TOKEN,value];else{for(i=1;i<list.length;i+=2)if(list[i]===MAGIC_TOKEN)break;list[i]=MAGIC_TOKEN,list[i+1]=value}}function
getOnKey(key){var ktype=typeof key,i,list;(!key||ktype!=='function'&&ktype!=='object')&&notObject(key,'WeakMap key'),list=key[myMagicIndexName];if(!list||list[0]!==key)return;for(i=1;i<list.length;i+=2)if(list[i]===MAGIC_TOKEN)return list[i+1];return}function
hasOnKey(key){var ktype=typeof key,i,list;(!key||ktype!=='function'&&ktype!=='object')&&notObject(key,'WeakMap key'),list=key[myMagicIndexName];if(!list||list[0]!==key)return false;for(i=1;i<list.length;i+=2)if(list[i]===MAGIC_TOKEN)return true;return false}if(opt_useKeyLifetime)return snowWhite({'set':markConstFunc(setOnKey),'get':markConstFunc(getOnKey),'has':markConstFunc(hasOnKey)});myValues=[];function
setOnTable(key,value){var index;switch(typeof key){case'object':case'function':if(null===key)return myValues.prim_null=value,void
0;index=getOnKey(key);if(value===void 0){if(index===void 0)return;setOnKey(key,void
0)}else index===void 0&&(index=myValues.length,setOnKey(key,index));break;case'string':index='str_'+key;break;default:index='prim_'+key}value===void
0?delete myValues[index]:(myValues[index]=value)}function getOnTable(key){var index;switch(typeof
key){case'object':case'function':return null===key?myValues.prim_null:(index=getOnKey(key),void
0===index?void 0:myValues[index]);case'string':return myValues['str_'+key];default:return myValues['prim_'+key]}}function
hasOnTable(key){var index;switch(typeof key){case'object':case'function':return null===key?'prim_null'in
myValues:(index=getOnKey(key),void 0!==index);case'string':return'str_'+key in myValues;default:return'prim_'+key
in myValues}}return snowWhite({'set':markConstFunc(setOnTable),'get':markConstFunc(getOnTable),'has':markConstFunc(hasOnTable)})}HostWeakMap=WeakMap,typeof
HostWeakMap==='function'?(typeof navigator!=='undefined'&&/Firefox/.test(navigator.userAgent)?(hostWeakMapOK=false):(hostWeakMapOK=true),WeakMap=markFunc(hostWeakMapOK?function(){var
result=HostWeakMap();return markFunc(result.get),result.get_v___=result,result.get_c___=false,result.get_w___=false,result.get_gw___=result,result.get_e___=result,result.get_m___=false,result.get_g___=false,result.get_s___=false,result.get_av___=false,markFunc(result.set),result.set_v___=result,result.set_c___=false,result.set_w___=false,result.set_gw___=result,result.set_e___=result,result.set_m___=false,result.set_g___=false,result.set_s___=false,result.set_av___=false,markFunc(result.has),result.has_v___=result,result.has_c___=false,result.has_w___=false,result.has_gw___=result,result.has_e___=result,result.has_m___=false,result.has_g___=false,result.has_s___=false,result.has_av___=false,result}:function
DoubleWeakMap(){var hmap=HostWeakMap(),omap=undefined;return snowWhite({'get':markConstFunc(function(key,opt_default){return hmap.has(key)?hmap.get(key):omap&&omap.has(key)?omap.get(key):opt_default}),'set':markConstFunc(function(key,value){try{hmap.set(key,value)}catch(e){omap||(omap=newTable(true)),omap.set(key,value)}}),'has':markConstFunc(function(key){return hmap.has(key)||(omap?omap.has(key):false)})})})):(WeakMap=markFunc(function(){return newTable(true)})),registeredImports=[];function
getId(imports){var id;return enforceType(imports,'object','imports'),'id___'in imports?(id=enforceType(imports.id___,'number','id')):(id=imports.id___=registeredImports.length),registeredImports[id]=imports,id}function
getImports(id){var result=registeredImports[enforceType(id,'number','id')];if(result===void
0)throw new Error('Internal: imports#',id,' unregistered');return result}function
unregister(imports){var id;enforceType(imports,'object','imports'),'id___'in imports&&(id=enforceType(imports.id___,'number','id'),registeredImports[id]=void
0)}defended=newTable(),def=markConstFunc(function(root){var defending=defended||newTable(),desc,i,keys,n,todo,val;defended=null,todo=[root];while(todo.length){val=todo.pop();if(val!==Object.prototype&&val!==Object(val))continue;if(defending.get(val))continue;defending.set(freeze(val),true),todo.push(stdGetPrototypeOf(val)),keys=val.ownKeys___();for(i=0,n=keys.length;i<n;++i)desc=val.GetOwnProperty___(keys[i]),desc.value&&todo.push(desc.value),desc.get&&todo.push(desc.get),desc.set&&todo.push(desc.set)}return defended=defending,root}),USELESS=Token('USELESS'),NO_RESULT=Token('NO_RESULT');function
identity(x){return x}function callWithEjector(attemptFunc,opt_failFunc){var failFunc=opt_failFunc||identity,disabled=false,token=new
Token('ejection'),stash=void 0;function ejector(result){throw disabled?new Error('ejector disabled'):(stash=result,token)}markConstFunc(ejector);try{try{return attemptFunc.m___('call',[USELESS,ejector])}finally{disabled=true}}catch(e){if(e===token)return failFunc.m___('call',[USELESS,stash]);throw e}}function
eject(opt_ejector,result){throw opt_ejector?(opt_ejector.m___('call',[USELESS,result]),new
Error('Ejector did not exit: ',opt_ejector)):new Error(result)}function makeTrademark(typename,table){return typename=''+typename,snowWhite({'toString':markConstFunc(function(){return typename+'Mark'}),'stamp':snowWhite({'toString':markConstFunc(function(){return typename+'Stamp'}),'mark___':markConstFunc(function(obj){return table.set(obj,true),obj})}),'guard':snowWhite({'toString':markConstFunc(function(){return typename+'T'}),'coerce':markConstFunc(function(specimen,opt_ejector){if(table.get(specimen))return specimen;eject(opt_ejector,'Specimen does not have the \"'+typename+'\" trademark')})})})}GuardMark=makeTrademark('Guard',newTable(true)),GuardT=GuardMark.guard,GuardStamp=GuardMark.stamp,freeze(GuardStamp.mark___(GuardT));function
Trademark(typename){var result=makeTrademark(typename,newTable(true));return freeze(GuardStamp.mark___(result.guard)),result}markConstFunc(Trademark);function
guard(g,specimen,opt_ejector){return g=GuardT.coerce(g),g.coerce(specimen,opt_ejector)}function
passesGuard(g,specimen){return g=GuardT.coerce(g),callWithEjector(markConstFunc(function(opt_ejector){return g.coerce(specimen,opt_ejector),true}),markConstFunc(function(ignored){return false}))}function
stamp(stamps,record){var i,numStamps;if(isFrozen(record))throw new TypeError(('Can\'t stamp frozen objects: '+record));stamps=slice.call(stamps,0),numStamps=stamps.length;for(i=0;i<numStamps;++i)if(!('mark___'in
stamps[i]))throw new TypeError(('Can\'t stamp with a non-stamp: '+stamps[i]));for(i=0;i<numStamps;++i)stamps[i].mark___(record);return freeze(record)}function
makeTableGuard(table,typename,errorMessage){var g=whitelistAll({'toString':markConstFunc(function(){return typename+'T'}),'coerce':markConstFunc(function(specimen,opt_ejector){if(Object(specimen)===specimen&&table.get(specimen))return specimen;eject(opt_ejector,errorMessage)})});return stamp([GuardStamp],g),g}function
makeSealerUnsealerPair(){var table=newTable(true),undefinedStandin={};function seal(payload){var
box;return payload===void 0&&(payload=undefinedStandin),box=Token('(box)'),table.set(box,payload),box}function
unseal(box){var payload=table.get(box);if(payload===void 0)throw new TypeError('Sealer/Unsealer mismatch');else
if(payload===undefinedStandin)return;return payload}return snowWhite({'seal':markConstFunc(seal),'unseal':markConstFunc(unseal)})}function
manifest(ignored){}function Type(x){switch(typeof x){case'undefined':return'Undefined';case'boolean':return'Boolean';case'string':return'String';case'number':return'Number';default:return x?'Object':'Null'}}attributeDefaults={'value':void
0,'get':void 0,'set':void 0,'writable':false,'enumerable':false,'configurable':false};function
isPrimitive(x){return Type(x)!=='Object'}function IsAccessorDescriptor(Desc){return Desc===void
0?false:'get'in Desc?true:'set'in Desc}function IsDataDescriptor(Desc){return Desc===void
0?false:'value'in Desc?true:'writable'in Desc}function IsGenericDescriptor(Desc){return Desc===void
0?false:!IsAccessorDescriptor(Desc)&&!IsDataDescriptor(Desc)}function FromPropertyDescriptor(Desc){var
obj;function copyProp(Desc,obj,name){obj.DefineOwnProperty___(name,{'value':Desc[name],'writable':true,'enumerable':true,'configurable':true})}return Desc===void
0?void 0:(obj={},IsDataDescriptor(Desc)?(copyProp(Desc,obj,'value'),copyProp(Desc,obj,'writable')):(copyProp(Desc,obj,'get'),copyProp(Desc,obj,'set')),copyProp(Desc,obj,'enumerable'),copyProp(Desc,obj,'configurable'),obj)}function
ToPropertyDescriptor(Obj){var desc,getter,setter;Type(Obj)!=='Object'&&notObject(Obj),desc={},Obj.HasProperty___('enumerable')&&(desc.enumerable=!!Obj.v___('enumerable')),Obj.HasProperty___('configurable')&&(desc.configurable=!!Obj.v___('configurable')),Obj.HasProperty___('value')&&(desc.value=Obj.v___('value')),Obj.HasProperty___('writable')&&(desc.writable=!!Obj.v___('writable')),Obj.HasProperty___('get')&&(getter=Obj.v___('get'),!isFunction(getter)&&getter!==void
0&&notFunction(getter,'getter'),desc.get=asFirstClass(getter)),Obj.HasProperty___('set')&&(setter=Obj.v___('set'),!isFunction(setter)&&setter!==void
0&&notFunction(setter,'setter'),desc.set=asFirstClass(setter));if('set'in desc||'get'in
desc){if('value'in desc)throw new TypeError('Property with get/set cannot have value.');if('writable'in
desc)throw new TypeError('Property with get/set cannot have writable.')}return desc}Object.prototype.GetOwnProperty___=function
GetOwnProperty___(P){var O=this,D;if(typeof P==='number'||''+ +P===P)return O.hasOwnProperty(P)?{'value':O[P],'writable':isWritable(O,'NUM___'),'configurable':isConfigurable(O,'NUM___'),'enumerable':true}:void
0;P=''+P;if(endsWith__.test(P))throw new TypeError('Property name may not end in double underscore.');return O.hasOwnProperty(P+'_v___')?(D={},hasValue(O,P)?(D.value=O[P],D.writable=isWritable(O,P)):O[P+'_av___']===O?(D.value=O.v___(P),D.writable=isWritable(O,P)):(D.get=getter(O,P),D.set=setter(O,P)),D.enumerable=isEnumerable(O,P),D.configurable=isConfigurable(O,P),D):void
0},Object.prototype.v___=function v___(P){var g;return P=''+P,isNumericName(P)?this[P]:(assertValidPropertyName(P),g=getter(this,P),g?g.f___(this):hasValue(this,P)?this[P]:void
0)},Object.prototype.w___=function w___(P,V){var thisExtensible=isExtensible(this),s;P=''+P,assertValidPropertyName(P);if(!thisExtensible){if(wouldExtend(this,P))throw new
TypeError(('Could not create the property \''+P+'\': '+this+' is not extensible.'))};V=asFirstClass(V);if(isNumericName(P)){if(isWritable(this,'NUM___'))return this[P]=V;throw new
TypeError(('The property \''+P+'\' is not writable.'))}if(this[P+'_v___']===false){s=setter(this,P);if(s)return s.f___(this,[V]),V;throw new
TypeError(('The property \''+P+'\' has no setter.'))}if(this[P+'_v___']===this){if(isWritable(this,P))return fastpathWrite(this,P),this[P]=V;throw new
TypeError(('The property \''+P+'\' is not writable.'))}if(!this.hasOwnProperty(P))return this.DefineOwnProperty___(P,{'value':V,'writable':true,'configurable':true,'enumerable':true}),V;throw new
TypeError(('The property \''+P+'\' is not writable.'))},Object.prototype.HasProperty___=function(P){return(isNumericName(P)?P:P+'_v___')in
this};function rawDelete(O,P){return delete O[P]&&delete O[P+'_v___']&&delete O[P+'_w___']&&delete
O[P+'_gw___']&&delete O[P+'_g___']&&delete O[P+'_s___']&&delete O[P+'_c___']&&delete
O[P+'_e___']&&delete O[P+'_m___']&&delete O[P+'_av___']}Object.prototype.c___=function(P){var
O=this,desc;P=''+P,desc=O.GetOwnProperty___(P);if(!desc)return true;if(desc.configurable){if(isNumericName(P)){if(isDeodorized(O,P))throw new
TypeError(('Cannot delete Firefox-specific antidote \''+P+'\' on '+O));return delete
O[P],true}return rawDelete(O,P),true}throw new TypeError(('Cannot delete \''+P+'\' on '+O))},Object.prototype.DefineOwnProperty___=function
DefineOwnProperty___(P,Desc){var O,allHaveAppearedAndAreTheSame,current,extensible,i,iddCurrent,iddDesc;if(typeof
P==='number'||''+ +P===P)throw new TypeError('Cannot define numeric properties.');O=this,P=''+P,current=O.GetOwnProperty___(P),extensible=Type(O)==='Object'&&O.ne___!==O;if(!current&&!extensible)throw new
TypeError('This object is not extensible.');if(!current&&extensible)return IsDataDescriptor(Desc)||IsGenericDescriptor(Desc)?(lookupVirtualizedProperty(P)?installVirtualizedPropertyParts(O,P,Desc):(O[P]=Desc.value,O[P+'_v___']=O,O[P+'_g___']=void
0,O[P+'_s___']=void 0,O[P+'_av___']=false),O[P+'_w___']=false,O[P+'_gw___']=Desc.writable?O:false,O[P+'_e___']=Desc.enumerable?O:false,O[P+'_c___']=Desc.configurable?O:false,O[P+'_m___']=false):(O[P]=Desc.configurable?void
0:O[P],O[P+'_v___']=false,O[P+'_w___']=O[P+'_gw___']=false,O[P+'_e___']=Desc.enumerable?O:false,O[P+'_c___']=Desc.configurable?O:false,O[P+'_g___']=Desc.get,O[P+'_s___']=Desc.set,O[P+'_m___']=false,O[P+'_av___']=false),true;if(!('value'in
Desc||'writable'in Desc||'enumerable'in Desc||'configurable'in Desc||'get'in Desc||'set'in
Desc))return true;allHaveAppearedAndAreTheSame=true;for(i in Desc){if(!Desc.hasOwnProperty(i))continue;if(!SameValue(current[i],Desc[i])){allHaveAppearedAndAreTheSame=false;break}}if(allHaveAppearedAndAreTheSame)return true;if(!current.configurable){if(Desc.configurable)throw new
TypeError(('The property \''+P+'\' is not configurable.'));if('enumerable'in Desc&&Desc.enumerable!==current.enumerable)throw new
TypeError(('The property \''+P+'\' is not configurable.'))}iddCurrent=IsDataDescriptor(current),iddDesc=IsDataDescriptor(Desc);if(IsGenericDescriptor(Desc));else
if(iddCurrent!==iddDesc){if(!current.configurable)throw new TypeError(('The property \''+P+'\' is not configurable.'));iddCurrent?(O[P]=void
0,O[P+'_v___']=false,O[P+'_w___']=O[P+'_gw___']=false,O[P+'_g___']=void 0,O[P+'_s___']=void
0,O[P+'_m___']=false,O[P+'_av___']=false):(lookupVirtualizedProperty(P)?installVirtualizedPropertyParts(O,P,Desc):(O[P]=Desc.value,O[P+'_v___']=O,O[P+'_g___']=void
0,O[P+'_s___']=void 0,O[P+'_m___']=false,O[P+'_av___']=false),O[P+'_w___']=O[P+'_gw___']=false)}else
if(iddCurrent&&iddDesc){if(!current.configurable){if(!current.writable&&Desc.writable)throw new
TypeError(('The property \''+P+'\' is not configurable.'));if(!current.writable){if('value'in
Desc&&!SameValue(Desc.value,current.value))throw new TypeError(('The property \''+P+'\' is not writable.'))}}}else
if(!current.configurable){if('set'in Desc&&!SameValue(Desc.set,current.set)||'get'in
Desc&&!SameValue(Desc.get,current.get))throw new TypeError(('The property \''+P+'\' is not configurable.'))};return iddDesc?(lookupVirtualizedProperty(P)?installVirtualizedPropertyParts(O,P,Desc):(O[P]=Desc.value,O[P+'_v___']=O,O[P+'_g___']=O[P+'_s___']=void
0,O[P+'_av___']=false),O[P+'_gw___']=Desc.writable?O:false):(O[P]=O[P],O[P+'_v___']=false,O[P+'_gw___']=false,O[P+'_g___']=Desc.get,O[P+'_s___']=Desc.set,O[P+'_av___']=false),O[P+'_e___']=Desc.enumerable?O:false,O[P+'_c___']=Desc.configurable?O:false,O[P+'_m___']=false,O[P+'_w___']=false,true};function
installVirtualizedPropertyParts(O,P,Desc){var value=Desc.value,hook=lookupVirtualizedProperty(P).opt_setterHook||identity;function
preSet(obj,newValue){return newValue=asFirstClass(newValue),hook.call(obj,newValue),newValue}Desc.doNotApplySetterHook___||(value=preSet(O,value)),O[P+'_v___']=false,O[P+'_w___']=false,O[P+'_g___']=markConstFunc(function
virtualizedPropertyGetter(){return value}),O[P+'_s___']=markConstFunc(function virtualizedPropertySetter(newValue){if(this===O)if(isWritable(O,P))value=preSet(O,newValue);else
throw new TypeError(('The property \''+P+'\' is not writable.'));else ToObject(this).DefineOwnProperty___(P,{'configurable':true,'enumerable':true,'writable':true,'value':newValue})}),O[P+'_m___']=false,O[P+'_av___']=O}function
ToUint32(input){return input>>>0}function ToObject(input){if(input===void 0||input===null)throw new
TypeError(('Cannot convert '+input+' to Object.'));return Object(input)}function
SameValue(x,y){return x===y?x!==0||1/x===1/y:x!==x&&y!==y}function asFirstClass(value){if(isFunction(value)&&!value.ok___){if(value===Function.prototype)throw new
Error('Cannot invoke Function.prototype.');if(!___.DISABLE_SECURITY_FOR_DEBUGGER)throw new
Error(('Internal: toxic function encountered!\n'+value));log('Internal: toxic function encountered!\n'+value)}return value}function
initializeMap(list){var result={},accessors={},hasAccessors=false,i,name,type;for(i=0;i<list.length;i+=2)if(typeof
list[i]==='string'){if(result.hasOwnProperty(list[i]))throw new SyntaxError(('Duplicate keys: '+list[i]));isNumericName(list[i])?(result[list[i]]=asFirstClass(list[i+1])):result.DefineOwnProperty___(list[i],{'value':asFirstClass(list[i+1]),'writable':true,'enumerable':true,'configurable':true})}else{hasAccessors=true,name=list[i][0];if(isNumericName(name))throw new
TypeError('Accessors not supported for numerics.');type=list[i][1],accessors[name]=accessors[name]||{};if(accessors[name].hasOwnProperty(type))throw new
SyntaxError(('Duplicate accessor keys: '+type+' '+list[i]));accessors[name][type]=asFirstClass(list[i+1])}if(hasAccessors)for(i
in accessors){if(!accessors.hasOwnProperty(i))continue;if(endsWith__.test(i))continue;result.DefineOwnProperty___(i,{'get':accessors[i].get,'set':accessors[i].set,'enumerable':true,'configurable':true})}return result}function
makePoisonPill(badThing){function poisonPill(){throw new TypeError((''+badThing+' is forbidden by ES5/strict'))}return markFunc(poisonPill)}poisonFuncCaller=makePoisonPill('A function\'s .caller'),poisonFuncArgs=makePoisonPill('A function\'s .arguments'),Function.prototype.f___=callFault,Function.prototype.i___=function(var_args){return this.f___(USELESS,arguments)},Function.prototype.new___=callFault,Function.prototype.DefineOwnProperty___('arguments',{'enumerable':false,'configurable':false,'get':poisonFuncArgs,'set':poisonFuncArgs}),Function.prototype.DefineOwnProperty___('caller',{'enumerable':false,'configurable':false,'get':poisonFuncCaller,'set':poisonFuncCaller}),poisonArgsCallee=makePoisonPill('arguments.callee'),poisonArgsCaller=makePoisonPill('arguments.caller');function
args(original){var result=initializeMap(['length',0]);return push.apply(result,original),result.CLASS___='Arguments',result.DefineOwnProperty___('callee',{'enumerable':false,'configurable':false,'get':poisonArgsCallee,'set':poisonArgsCallee}),result.DefineOwnProperty___('caller',{'enumerable':false,'configurable':false,'get':poisonArgsCaller,'set':poisonArgsCaller}),result}function
isIn(name,obj){return Type(obj)!=='Object'&&notObject(obj),obj.HasProperty___(name)}virtualizedProperties={},virtualizedPropertiesFrozen=false;function
lookupVirtualizedProperty(name){var key=name+'$';return virtualizedProperties.hasOwnProperty(key)?virtualizedProperties[key]:(virtualizedPropertiesFrozen||(virtualizedProperties[key]=false),undefined)}function
virtualize(obj,name,opt_initialMethod,opt_setterHook){var key;if(virtualizedPropertiesFrozen)throw new
Error('Internal: virtualize() called late');key=name+'$';if(virtualizedProperties.hasOwnProperty(key)){if(!virtualizedProperties[key])throw new
Error(('Internal: virtualize() called after first mention ('+obj+'.'+name+')'));else
if(opt_setterHook)throw new Error(('Internal: Only the first virtualize() may set a hook ('+obj+'.'+name+')'))}else
virtualizedProperties[key]={'opt_setterHook':opt_setterHook};obj.DefineOwnProperty___(name,{'enumerable':false,'configurable':false,'value':opt_initialMethod?markFunc(opt_initialMethod):obj[name]?markFunc(obj[name]):void
0,'doNotApplySetterHook___':true})}function virtualizeDone(){virtualizedPropertiesFrozen=true}markFunc(decodeURI),markFunc(decodeURIComponent),markFunc(encodeURI),markFunc(encodeURIComponent),Object.f___=markFunc(function(dis,as){var
len=as.length;return len===0||as[0]===null||as[0]===void 0?{}:ToObject(as[0])}),Object.new___=markFunc(function(value){return Object.f___(USELESS,[value])}),Object.DefineOwnProperty___('prototype',{'value':Object.prototype,'writable':false,'enumerable':false,'configurable':false}),Object.getPrototypeOf||(Object.getPrototypeOf=function(obj){var
constr;return Type(obj)!=='Object'&&notObject(obj),obj.hasOwnProperty('Prototype___')||(({}).__proto__===Object.prototype?(obj.Prototype___=obj.__proto__):(constr=directConstructor(obj),constr===BASE_OBJECT_CONSTRUCTOR?(obj.Prototype___=obj.baseProto___):constr===void
0?(obj.Prototype___=null):(obj.Prototype___=constr.prototype))),obj.Prototype___}),stdGetPrototypeOf=Object.getPrototypeOf,stdGetOwnPropertyDescriptor=function(obj,P){var
desc,name;return Type(obj)!=='Object'&&notObject(obj),obj.v___===deferredV&&installFunctionInstanceProps(obj),name=''+P,desc=obj.GetOwnProperty___(name),desc?FromPropertyDescriptor(desc):void
0},virtualize(Object,'getOwnPropertyDescriptor',stdGetOwnPropertyDescriptor),virtualize(Object,'getOwnPropertyNames',function(obj){return obj.v___===deferredV&&installFunctionInstanceProps(obj),obj.ownKeys___()});function
beget(proto){var result;if(proto===null)throw new TypeError('Cannot beget from null.');if(proto===void
0)throw new TypeError('Cannot beget from undefined.');function F(){}return F.prototype=proto,result=new
F,result}Object.create=function(O,opt_Properties){var type=Type(O),obj;if(type==='Null')throw new
TypeError('ES5/3 can not support Object.create(null).');else if(type!=='Object')notObject(O);return obj=beget(O),opt_Properties!==void
0&&DefineProperties(obj,opt_Properties),obj},Object.defineProperty=function(O,P,Attributes){var
desc,name;return Type(O)!=='Object'&&notObject(O),name=''+P,desc=ToPropertyDescriptor(Attributes),O.DefineOwnProperty___(name,desc),O};function
DefineProperties(O,Properties){var P,desc,descObj,descriptors,i,len,names,props;Type(O)!=='Object'&&notObject(O),props=ToObject(Properties),names=ownEnumKeys(props),descriptors=[],len=names.length;for(i=0;i<len;++i)P=names[i],descObj=props.v___(P),desc=ToPropertyDescriptor(descObj),descriptors.push(desc);for(i=0;i<len;++i)P=names[i],desc=descriptors[i],O.DefineOwnProperty___(P,desc);return O}Object.defineProperties=DefineProperties,Object.seal=function(O){return Type(O)!=='Object'&&notObject(O),O.seal___()},Object.prototype.seal___=function(){var
P,i,m;this.v___===deferredV&&this.v___('length');for(i in this){if(!this.hasOwnProperty(i))continue;if(isNumericName(i))continue;m=i.match(endsWith_v___);if(!m)continue;P=m[1],this[P+'_c___']=false}return this.hasNumerics___()||(this.NUM____v___=this,this.NUM____gw___=this,this.NUM____w___=this,this.NUM____m___=false,this.NUM____e___=this,this.NUM____g___=void
0,this.NUM____s___=void 0,this.NUM____av___=false),this.NUM____c___=false,this.ne___=this,this};function
whitelistAll(obj,opt_deep){var keys=fastOwnKeys(obj),i,k,n,val;for(k=0,n=keys.length;k<n;++k)i=keys[k],val=obj[i],i.substr(i.length-2)!=='__'&&!(i+'_v___'in
obj)&&(opt_deep&&val&&typeof val==='object'&&whitelistAll(val,true),obj[i+'_v___']=obj,obj[i+'_w___']=false,obj[i+'_gw___']=false,obj[i+'_e___']=obj,obj[i+'_c___']=false,obj[i+'_g___']=void
0,obj[i+'_s___']=void 0,obj[i+'_m___']=false,obj[i+'_av___']=false,val&&val.f___===Function.prototype.f___?classProp.call(val)==='[object Function]'&&markFunc(val):classProp.call(val)==='[object Function]'&&(val.ok___=true));return obj}function
snowWhite(obj){return freeze(whitelistAll(obj))}function makeDefensibleFunction(f){return markConstFunc(function(_){return f.apply(USELESS,arguments)})}function
makeDefensibleObject(descriptors){var td={},k;for(k in descriptors){if(!descriptors.hasOwnProperty(k))continue;if(isNumericName(k))throw'Cannot define numeric property: '+k;td.DefineOwnProperty___(k,{'value':FromPropertyDescriptor(descriptors[k]),'enumerable':true,'writable':false})}return Object.seal(Object.create(Object.prototype,td))}function
freeze(obj){return Type(obj)!=='Object'&&notObject(obj),obj.freeze___()}Object.freeze=freeze,Object.preventExtensions=function(obj){return Type(obj)!=='Object'&&notObject(obj),obj.pe___()},Object.prototype.pe___=function(){return this.hasNumerics___()||(this.NUM____v___=this,this.NUM____e___=this,this.NUM____g___=void
0,this.NUM____s___=void 0,this.NUM____c___=this,this.NUM____gw___=this,this.NUM____w___=this,this.NUM____m___=false,this.NUM____av___=false),this.ne___=this,this},Object.isSealed=function(O){var
i;Type(O)!=='Object'&&notObject(O);for(i in O){if(endsWith__.test(i))continue;if(!O.hasOwnProperty(i))continue;if(isNumericName(i))continue;if(O[i+'_c___'])return false}return O.ne___===O},Object.isFrozen=isFrozen,Object.isExtensible=isExtensible,virtualize(Object,'keys',ownEnumKeys),(function(){var
objectStaticMethods=['getPrototypeOf','create','defineProperty','defineProperties','seal','freeze','preventExtensions','isSealed','isFrozen','isExtensible'],len=objectStaticMethods.length,i,name;for(i=0;i<len;++i)name=objectStaticMethods[i],Object.DefineOwnProperty___(name,{'value':markFunc(Object[name]),'writable':true,'enumerable':false,'configurable':true})})(),Object.DefineOwnProperty___('constructor',{'value':Object,'writable':false,'enumerable':false,'configurable':false}),Object.prototype.toString=markFunc(function(){return this.CLASS___?'[object '+this.CLASS___+']':classProp.call(this)}),virtualize(Object.prototype,'toString',undefined,function
toStringSetterHook(val){isFunction(val)||notFunction(val),this.toString=markFunc(function(var_args){return val.f___(safeDis(this),arguments)})}),markFunc(Object.prototype.valueOf),virtualize(Object.prototype,'valueOf',undefined,function
valueOfSetterHook(val){isFunction(val)||notFunction(val),this.valueOf=markFunc(function(var_args){return val.f___(safeDis(this),arguments)})}),virtualize(Object.prototype,'hasOwnProperty',function(P){return isNumericName(P)?this.hasOwnProperty(P):this.HasOwnProperty___(P)}),virtualize(Object.prototype,'propertyIsEnumerable',function(V){return isEnumerable(this,''+V)}),virtualize(Object.prototype,'toLocaleString'),virtualize(Object.prototype,'isPrototypeOf'),freeze(Object.prototype),FakeFunction=function(){throw new
Error('Internal: FakeFunction should not be directly invocable.')},FakeFunction.toString=(function(str){return markFunc(function(){return str})})(Function.toString()),virtualize(FakeFunction,'toString'),Function.f___=FakeFunction.f___=markFunc(function(){throw new
Error('Invoking the Function constructor is unsupported.')}),Function.new___=FakeFunction.new___=markFunc(function(){throw new
Error('Constructing functions dynamically is unsupported.')}),FakeFunction.DefineOwnProperty___('prototype',{'value':Function.prototype,'writable':false,'enumerable':false,'configurable':false}),Function.prototype.DefineOwnProperty___('constructor',{'value':FakeFunction,'writable':true,'enumerable':false,'configurable':false}),(function(){var
orig=Function.prototype.toString;Function.prototype.toString=markFunc(function(){return this.toString___?this.toString___():orig.call(this)}),virtualize(Function.prototype,'toString')})(),virtualize(Function.prototype,'call',function(dis,var_args){return this.apply(safeDis(dis),slice.call(arguments,1))}),virtualize(Function.prototype,'apply',function(dis,as){return this.apply(safeDis(dis),as?slice.call(as,0):void
0)}),Function.prototype.bind=function(self,var_args){var thisFunc=safeDis(this),leftArgs=slice.call(arguments,1);function
funcBound(var_args){var args=leftArgs.concat(slice.call(arguments,0));return thisFunc.apply(safeDis(self),args)}return markFunc(funcBound),funcBound.f___=funcBound.apply,funcBound.ok___=true,rawDelete(funcBound,'prototype'),funcBound.new___=function(){throw'Constructing the result of a bind() not yet implemented.'},funcBound},virtualize(Function.prototype,'bind'),markFunc(Array),Array.DefineOwnProperty___('prototype',{'value':Array.prototype,'writable':false,'enumerable':false,'configurable':false}),Array.isArray=markFunc(isArray),Array.DefineOwnProperty___('isArray',{'value':Array.isArray,'writable':true,'enumerable':false,'configurable':true}),Array.prototype.DefineOwnProperty___('constructor',{'value':Array,'writable':true,'enumerable':false,'configurable':false}),markFunc(Array.prototype.toString),virtualize(Array.prototype,'toString'),(function(){var
methods=['toLocaleString','concat','join','pop'],i,len;for(i=0,len=methods.length;i<len;++i)virtualize(Array.prototype,methods[i])})();function
whitelistLengthIfItExists(dis){'length'in dis&&!('length_v___'in dis)&&dis.DefineOwnProperty___('length',{'value':dis.length,'writable':true,'configurable':true,'enumerable':true})}function
guardedVirtualize(obj,name){var orig=obj[name];virtualize(obj,name,function guardedArrayMethod(var_args){var
dis,result;if(!isExtensible(this))throw new TypeError('This object is not extensible.');return dis=safeDis(this),result=orig.apply(dis,arguments),whitelistLengthIfItExists(dis),result})}(function(){var
methods=['push','reverse','shift','splice','unshift'],i,len;for(i=0,len=methods.length;i<len;++i)guardedVirtualize(Array.prototype,methods[i])})(),virtualize(Array.prototype,'slice'),virtualize(Array.prototype,'sort',function(comparefn){var
result;if(!isWritable(this,'NUM___'))throw new TypeError('Cannot sort an object whose numeric properties are not writable.');if(!isExtensible(this))throw new
TypeError('Cannot sort an object that is not extensible.');return result=comparefn?sort.call(this,markFunc(function(var_args){return comparefn.f___(this,arguments)})):sort.call(this),whitelistLengthIfItExists(this),result}),Array.prototype.indexOf=markFunc(function(value,fromIndex){var
len=this.length>>>0,i;if(!len)return -1;i=fromIndex||0;if(i>=len)return -1;i<0&&(i+=len);for(;i<len;++i){if(!this.hasOwnProperty(i))continue;if(value===this[i])return i}return -1}),virtualize(Array.prototype,'indexOf'),Array.prototype.lastIndexOf=function(value,fromIndex){var
len=this.length,i;if(!len)return -1;i=arguments[1]||len,i<0&&(i+=len),i=min(i,len-1);for(;i>=0;--i){if(!this.hasOwnProperty(i))continue;if(value===this[i])return i}return -1},virtualize(Array.prototype,'lastIndexOf');function
createOrWrap(obj,name,fun){var implementation;obj[name]?(implementation=(function(orig){return function(block){var
a=slice.call(arguments,0);return a[0]=markFunc(function(var_args){return block.f___(this,arguments)}),orig.apply(this,a)}})(obj[name])):(implementation=fun),markFunc(implementation),virtualize(obj,name,implementation)}createOrWrap(Array.prototype,'every',function(block,thisp){var
len=this.length>>>0,i;for(i=0;i<len;++i)if(!block.f___(thisp,[this[i]]))return false;return true}),createOrWrap(Array.prototype,'some',function(block,thisp){var
len=this.length>>>0,i;for(i=0;i<this.length;++i)if(block.f___(thisp,[this[i]]))return true;return false}),virtualize(Array.prototype,'forEach',function(block,thisp){var
len=this.length>>>0,i;for(i=0;i<len;++i)i in this&&block.f___(thisp,[this[i],i,this])}),createOrWrap(Array.prototype,'map',function(fun,thisp){var
len=this.length>>>0,i,res;isFunction(fun)||notFunction(fun),res=new Array(len);for(i=0;i<len;++i)i
in this&&(res[i]=fun.f___(thisp,[this[i],i,this]));return res}),createOrWrap(Array.prototype,'filter',function(block,thisp){var
values=[],len=this.length>>>0,i;for(i=0;i<len;++i)block.f___(thisp,[this[i]])&&values.push(this[i]);return values}),createOrWrap(Array.prototype,'reduce',function(fun){var
len=this.length>>>0,i,rv;isFunction(fun)||notFunction(fun);if(len===0&&arguments.length===1)throw new
TypeError('Expected an initial value or a non-empty array.');i=0,rv=void 0;if(arguments.length>=2)rv=arguments[1];else
do{if(i in this){rv=this[i++];break}if(++i>=len)throw new TypeError('Expected non-empty array.')}while(true);for(;i<len;++i)i
in this&&(rv=fun.f___(USELESS,[rv,this[i],i,this]));return rv}),createOrWrap(Array.prototype,'reduceRight',function(fun){var
len=this.length>>>0,i,rv;isFunction(fun)||notFunction(fun);if(len===0&&arguments.length===1)throw new
TypeError('Expected an initial value or a non-empty array.');i=len-1,rv=void 0;if(arguments.length>=2)rv=arguments[1];else
do{if(i in this){rv=this[i--];break}if(--i<0)throw new TypeError('Expected a non-empty array.')}while(true);for(;i>=0;--i)i
in this&&(rv=fun.f___(USELESS,[rv,this[i],i,this]));return rv}),markFunc(String),String.DefineOwnProperty___('prototype',{'value':String.prototype,'writable':false,'enumerable':false,'configurable':false}),virtualize(String,'fromCharCode'),String.prototype.DefineOwnProperty___('constructor',{'value':String.prototype.constructor,'writable':true,'enumerable':false,'configurable':false}),markFunc(String.prototype.toString),virtualize(String.prototype,'toString'),markFunc(String.prototype.valueOf),virtualize(String.prototype,'valueOf'),(function(){var
methods=['charAt','charCodeAt','concat','indexOf','lastIndexOf','localeCompare','slice','substring','toLowerCase','toLocaleLowerCase','toUpperCase','toLocaleUpperCase','substr'],len=methods.length,i;for(i=0;i<len;++i)virtualize(String.prototype,methods[i])})();function
enforceMatchable(regexp){if(regexp instanceof RegExp){if(isFrozen(regexp))throw new
Error(('Can\'t match with frozen RegExp: '+regexp));return false}return true}function
tameStringRegExp(orig){return markFunc(function(regexp){var cast=enforceMatchable(regexp),result=orig.call(this,cast?''+regexp:regexp);return result!==null&&(grantRead(result,'index'),grantRead(result,'input')),result})}(function(){var
methods=['match','search','split'],i,len;for(i=0,len=methods.length;i<len;++i)virtualize(String.prototype,methods[i],tameStringRegExp(String.prototype[methods[i]]))})(),virtualize(String.prototype,'replace',function(searcher,replacement){var
cast=enforceMatchable(searcher);return isFunction(replacement)?(replacement=asFirstClass(replacement)):(replacement=''+replacement),replace.call(this,cast?''+searcher:searcher,replacement)}),trimBeginRegexp=/^\s\s*/,trimEndRegexp=/\s\s*$/,virtualize(String.prototype,'trim',function(){return(''+this).replace(trimBeginRegexp,'').replace(trimEndRegexp,'')}),markFunc(Boolean),Boolean.DefineOwnProperty___('prototype',{'value':Boolean.prototype,'writable':false,'enumerable':false,'configurable':false}),Boolean.prototype.DefineOwnProperty___('constructor',{'value':Boolean.prototype.constructor,'writable':true,'enumerable':false,'configurable':false}),markFunc(Boolean.prototype.toString),virtualize(Boolean.prototype,'toString'),markFunc(Boolean.prototype.valueOf),virtualize(Boolean.prototype,'valueOf'),markFunc(Number),(function(){var
props=['prototype','MAX_VALUE','MIN_VALUE','NEGATIVE_INFINITY','POSITIVE_INFINITY'],len=props.length,i;for(i=0;i<len;++i)Number.DefineOwnProperty___(props[i],{'value':Number[props[i]],'writable':false,'enumerable':false,'configurable':false})})(),Number.prototype.DefineOwnProperty___('constructor',{'value':Number.prototype.constructor,'writable':true,'enumerable':false,'configurable':false}),markFunc(Number.prototype.toString),virtualize(Number.prototype,'toString'),markFunc(Number.prototype.valueOf),virtualize(Number.prototype,'valueOf'),(function(){var
methods=['toLocaleString','toFixed','toExponential','toPrecision'],len=methods.length,i;for(i=0;i<len;++i)virtualize(Number.prototype,methods[i])})(),(function(){var
props=['E','LN10','LN2','LOG2E','LOG10E','PI','SQRT1_2','SQRT2'],len=props.length,i;for(i=0;i<len;++i)Math.DefineOwnProperty___(props[i],{'value':Math[props[i]],'writable':false,'enumerable':false,'configurable':false})})(),(function(){var
methods=['abs','acos','asin','atan','atan2','ceil','cos','exp','floor','log','max','min','pow','random','round','sin','sqrt','tan'],len=methods.length,i;for(i=0;i<len;++i)virtualize(Math,methods[i])})(),markFunc(Date),Date.DefineOwnProperty___('prototype',{'value':Date.prototype,'writable':false,'enumerable':false,'configurable':false}),(function(){var
staticMethods=['parse','UTC','now'],len=staticMethods.length,i;for(i=0;i<len;++i)virtualize(Date,staticMethods[i])})(),Date.prototype.DefineOwnProperty___('constructor',{'value':Date.prototype.constructor,'writable':true,'enumerable':false,'configurable':false}),markFunc(Date.prototype.toString),virtualize(Date.prototype,'toString'),markFunc(Date.prototype.valueOf),virtualize(Date.prototype,'valueOf'),(function(){var
methods=['toDateString','toTimeString','toLocaleString','toLocaleDateString','toLocaleTimeString','getTime','getFullYear','getMonth','getDate','getDay','getHours','getMinutes','getSeconds','getUTCSeconds','getUTCMinutes','getUTCHours','getUTCDay','getUTCDate','getUTCMonth','getUTCFullYear','getMilliseconds','getTimezoneOffset','toUTCString','toISOString','toJSON'],i;for(i=0;i<methods.length;++i)virtualize(Date.prototype,methods[i])})(),(function(){var
methods=['setTime','setMilliseconds','setUTCMilliseconds','setSeconds','setUTCSeconds','setMinutes','setUTCMinutes','setHours','setUTCHours','setDate','setUTCDate','setMonth','setUTCMonth','setFullYear','setUTCFullYear'],proto=Date.prototype,i;for(i=0;i<methods.length;++i)virtualize(proto,methods[i],(function(method){return function(varArgs){if(this===proto)throw new
TypeError('Cannot change the internal state of Date.prototype');if(!(this instanceof
Date))throw new TypeError('Cannot call this method on a non-Date or a cross-frame Date object.');return method.apply(this,arguments)}})(proto[methods[i]]))})(),RegExp.f___=markFunc(function(dis___,as){var
pattern=as[0],flags=as[1];if(classProp.call(pattern)==='[object RegExp]'&&flags===void
0)return pattern;switch(as.length){case 0:return new RegExp.new___;case 1:return new
RegExp.new___(pattern);default:return new RegExp.new___(pattern,flags)}}),RegExp.new___=markFunc(function(pattern,flags){var
i,instanceProps,re;switch(arguments.length){case 0:re=new RegExp;break;case 1:re=new
RegExp(pattern);break;default:re=new RegExp(pattern,flags)}instanceProps=['source','global','ignoreCase','multiline'];for(i=0;i<instanceProps.length;++i)re.DefineOwnProperty___(instanceProps[i],{'value':re[instanceProps[i]],'writable':false,'enumerable':false,'configurable':false});return re.DefineOwnProperty___('lastIndex',{'value':re.lastIndex,'writable':true,'enumerable':false,'configurable':false}),re}),RegExp.DefineOwnProperty___('prototype',{'value':RegExp.prototype,'writable':false,'enumerable':false,'configurable':false}),RegExp.prototype.DefineOwnProperty___('constructor',{'value':RegExp,'writable':true,'enumerable':false,'configurable':false}),virtualize(RegExp.prototype,'exec',function(specimen){var
m=RegExp.prototype.exec.call(safeDis(this),specimen);return m&&(grantRead(m,'index'),grantRead(m,'input')),m}),virtualize(RegExp.prototype,'test',function(specimen){return RegExp.prototype.test.call(safeDis(this),specimen)}),markFunc(Error),Error.DefineOwnProperty___('prototype',{'value':Error.prototype,'enumerable':false,'configurable':false,'writable':true}),Error.prototype.DefineOwnProperty___('constructor',{'value':Error,'enumerable':false,'configurable':false,'writable':true}),Error.prototype.DefineOwnProperty___('name',{'value':'Error','enumerable':false,'configurable':false,'writable':true}),Error.prototype.DefineOwnProperty___('message',{'value':'','enumerable':false,'configurable':false,'writable':true}),markFunc(Error.prototype.toString),virtualize(Error.prototype,'toString'),markFunc(EvalError),markFunc(RangeError),markFunc(ReferenceError),markFunc(SyntaxError),markFunc(TypeError),markFunc(URIError),virtualizeDone(),itemMap=WeakMap(),lengthMap=WeakMap(),lengthGetter=markConstFunc(function(){var
getter=lengthMap.get(this);return getter?getter.i___():void 0}),nativeProxies=Proxy&&(function(){var
obj={'0':'hi'},p=Proxy.create({'get':function(O,P){return obj[P]}});return p[0]==='hi'})(),numericGetters=(function(){var
obj={};try{defProp(obj,0,{'get':function(){return obj}});if(obj[0]!==obj)return false}catch(_){return false}return true})(),nativeProxies?(function(){var
del,get,gopn,gpn,has,hasOwn,ownPropDesc,propDesc;ArrayLike=markFunc(function(proto,getItem,getLength){var
obj;Type(proto)!=='Object'&&notObject(proto,'proto');if(!(proto instanceof ArrayLike))throw new
TypeError('Expected proto to be instanceof ArrayLike.');return obj=beget(proto),itemMap.set(obj,getItem),lengthMap.set(obj,getLength),obj}),propDesc=function(P){var
opd=ownPropDesc(P);return opd||gopd(Object.prototype,P)},ownPropDesc=function(P){var
get;return P=''+P,P==='length'?{'get':lengthGetter}:isNumericName(P)?(get=markConstFunc(function(){var
getter=itemMap.get(this);return getter?getter.i___(+P):void 0}),{'get':get,'enumerable':true,'configurable':true}):void
0},get=function(O,P){var getter;return P=''+P,P==='length'?lengthGetter.f___(O,[]):isNumericName(P)?(getter=itemMap.get(O),getter?getter.i___(+P):void
0):Object.prototype[P]},has=function(P){return P=''+P,P==='length'||isNumericName(P)||P
in Object.prototype},hasOwn=function(P){return P=''+P,P==='length'||isNumericName(P)},gpn=function(){var
result=gopn(),objPropNames=Object.getOwnPropertyNames(Object.prototype);return result.push.apply(result,objPropNames),result},gopn=function(){return['length']},del=function(P){return P=''+P,!(P==='length'||''+
+P===P)},ArrayLike.prototype=Proxy.create({'getPropertyDescriptor':propDesc,'getOwnPropertyDescriptor':ownPropDesc,'get':get,'has':has,'hasOwn':hasOwn,'getPropertyNames':gpn,'getOwnPropertyNames':gopn,'delete':del,'fix':function(){return}},Object.prototype),ArrayLike.DefineOwnProperty___('prototype',{'value':ArrayLike.prototype}),freeze(ArrayLike),makeArrayLike=markFunc(function(){return ArrayLike}),makeArrayLike.canBeFullyLive=true})():numericGetters?(function(){var
BiggestArrayLike,maxLen;function nextUInt31PowerOf2(v){if(!(isFinite(v)&&v>=0))throw new
RangeError((v+' not \x3e= 0'));return v&=2147483647,v|=v>>1,v|=v>>2,v|=v>>4,v|=v>>8,v|=v>>16,v+1}BiggestArrayLike=void
0,maxLen=0,makeArrayLike=markFunc(function(length){var BAL,i,len;length=+length,isFinite(length)&&length>=0||(length=0);if(!BiggestArrayLike||length>maxLen){len=nextUInt31PowerOf2(length),BAL=markFunc(function(proto,getItem,getLength){var
obj;Type(proto)!=='Object'&&notObject(proto,'proto');if(!(proto instanceof BAL))throw new
TypeError('Expected proto to be instanceof ArrayLike.');return obj=beget(proto),itemMap.set(obj,getItem),lengthMap.set(obj,getLength),obj});for(i=0;i<len;++i)(function(j){defProp(BAL.prototype,j,{'get':markConstFunc(function(){var
itemGetter=itemMap.get(this);return itemGetter?itemGetter.i___(j):void 0}),'enumerable':true})})(i);defProp(BAL.prototype,'length',{'get':lengthGetter}),BAL.DefineOwnProperty___('prototype',{'value':BAL.prototype}),BAL.prototype.DefineOwnProperty___('constructor',{'value':BAL}),freeze(BAL),freeze(BAL.prototype),BiggestArrayLike=BAL,maxLen=len}return BiggestArrayLike}),makeArrayLike.canBeFullyLive=false})():(ArrayLike=markFunc(function(proto,getItem,getLength){var
i,len,obj;Type(proto)!=='Object'&&notObject(proto,'proto'),obj=beget(proto),len=+getLength.i___(),obj.DefineOwnProperty___('length',{'value':len});for(i=0;i<len;++i)obj[i]=getItem.i___(i);return isWritable(obj,'NUM___'),obj.NUM____w___=false,obj}),ArrayLike.DefineOwnProperty___('prototype',{'value':ArrayLike.prototype}),ArrayLike.prototype.DefineOwnProperty___('constructor',{'value':ArrayLike}),freeze(ArrayLike),freeze(ArrayLike.prototype),makeArrayLike=markFunc(function(){return ArrayLike}),makeArrayLike.canBeFullyLive=false),makeArrayLike.DefineOwnProperty___('canBeFullyLive',{'value':makeArrayLike.canBeFullyLive,'enumerable':true}),defaultDerivedTraps={'has':function(name){var
dis=safeDis(this);return!!(dis.getPropertyDescriptor_m___?dis.getPropertyDescriptor(name):dis.m___('getPropertyDescriptor',[name]))},'hasOwn':function(name){var
dis=safeDis(this);return!!(dis.getOwnPropertyDescriptor_m___?dis.getOwnPropertyDescriptor(name):dis.m___('getOwnPropertyDescriptor',[name]))},'get':function(proxy,name){var
dis=safeDis(this),desc=dis.getPropertyDescriptor_m___?dis.getPropertyDescriptor(name):dis.m___('getPropertyDescriptor',[name]),get;return desc===void
0?void 0:'value_v___'in desc?desc.value_v___?desc.value:desc.v___('value'):(get=desc.get_v___?desc.get:desc.v___('get'),isFunction(get)?get.f___(safeDis(proxy),[]):void
0)},'set':function(proxy,name,val){var dis=safeDis(this),desc=dis.getOwnPropertyDescriptor_m___?dis.getOwnPropertyDescriptor(name):dis.m___('getOwnPropertyDescriptor',[name]),set;if(desc)return'writable_v___'in
desc?(desc.writable_v___?desc.writable:desc.v___('writable'))?(desc.value_w___===desc?(desc.value=val):desc.w___('value',val),dis.defineProperty_m___?dis.defineProperty(name,desc):dis.m___('defineProperty',[name,desc]),true):false:(set=desc.set_v___?desc.set:desc.v___('set'),isFunction(set)?(set.f___(safeDis(proxy),[val]),true):false);desc=dis.getPropertyDescriptor_m___?dis.getPropertyDescriptor(name):dis.m___('getPropertyDescriptor',[name]);if(desc)if('writable_v___'in
desc)if(desc.writable_v___?desc.writable:desc.v___('writable'));else return false;else
return set=desc.set_v___?desc.set:desc.v___('set'),isFunction(set)?(set.f___(safeDis(proxy),[val]),true):false;return desc=initializeMap(['value',val,'writable',true,'enumerable',true,'configurable',true]),dis.defineProperty_m___?dis.defineProperty(name,desc):dis.m___('defineProperty',[name,desc]),true},'enumerate':function(){var
dis=safeDis(this),names=dis.getPropertyNames_m___?dis.getPropertyNames():dis.m___('getPropertyNames',[]),filter=markFunc(function(name){var
desc=dis.getPropertyDescriptor_m___?dis.getPropertyDescriptor(name):dis.m___('getPropertyDescriptor',[name]);return desc.enumerable_v___?desc.enumerable:desc.v___('enumerable')});return names.filter_m___?names.filter(filter):names.m___('filter',[filter])},'keys':function(){var
dis=safeDis(this),names=dis.getOwnPropertyNames_m___?dis.getOwnPropertyNames():dis.m___('getOwnPropertyNames',[]),filter=markFunc(function(name){var
desc=dis.getOwnPropertyDescriptor_m___?dis.getOwnPropertyDescriptor(name):dis.m___('getOwnPropertyDescriptor',[name]);return desc.enumerable_v___?desc.enumerable:desc.v___('enumerable')});return names.filter_m___?names.filter(filter):names.m___('filter',[filter])}};function
prepareProxy(proxy,handler){proxy.proxy___=proxy,proxy.v___=function(P){var get;if(this!==proxy)throw new
TypeError('Inheritance from proxies not implemented yet.');return P=''+P,''+ +P===P?proxy[P]:(assertValidPropertyName(P),get=handler.get_v___?handler.get:handler.v___('get'),isFunction(get)?get.f___(handler,[proxy,P]):defaultDerivedTraps.get.apply(handler,[proxy,P]))},proxy.w___=function(P,V){var
result,set;if(this!==proxy)throw new TypeError('Inheritance from proxies not implemented yet.');P=''+P,V=asFirstClass(V);if(''+
+P===P)return proxy[P]=V;assertValidPropertyName(P),set=handler.set_v___?handler.set:handler.v___('set'),isFunction(set)?(result=set.f___(handler,[proxy,P,V])):(result=defaultDerivedTraps.set.apply(handler,[proxy,P,V]));if(!result)throw new
TypeError(('Failed to set '+P));return V},proxy.c___=function(P){var deleter,result;if(this!==proxy)throw new
TypeError('Inheritance from proxies not implemented yet.');P=''+P,''+ +P===P&&delete
proxy[P],assertValidPropertyName(P),deleter=handler.delete_v___?handler['delete']:handler.v___('delete'),result=deleter.f___(handler,[P]);if(!result)throw new
TypeError(('Unable to delete '+P));return true},proxy.m___=function(P,args){var
get,method;if(this!==proxy)throw new TypeError('Inheritance from proxies not implemented yet.');return P=''+P,''+
+P===P?(method=proxy[P]):(assertValidPropertyName(P),get=handler.get_v___?handler.get:handler.v___('get'),isFunction(get)?(method=get.f___(handler,[proxy,P])):(method=defaultDerivedTraps.get.apply(handler,[proxy,P]))),method.f___(proxy,args)},proxy.e___=function(){var
enumerate,i,len,name,names,result;if(this!==proxy)throw new TypeError('Inheritance from proxies not implemented yet.');enumerate=handler.enumerate___?handler.enumerate:handler.v___('enumerate'),isFunction(enumerate)?(names=enumerate.f___(handler,[])):(names=defaultDerivedTraps.enumerate.apply(handler,[])),result={};for(i=0,len=names.length;i<len;++i)name=''+names[i],assertValidPropertyName(name),result.DefineOwnProperty___(name,{'enumerable':true});return result},proxy.keys___=function(){var
i,keys,len,name,names,result,seen;if(this!==proxy)throw new TypeError('Inheritance from proxies not implemented yet.');keys=handler.keys_v___?handler.keys:handler.v___('keys'),isFunction(keys)?(names=keys.f___(handler,[])):(names=defaultDerivedTraps.keys.apply(handler,[])),result=[],len=names.length,seen={};for(i=0;i<len;++i){name=''+names[i],assertValidPropertyName(name);if(seen[name])continue;result.push(''+name),seen[name]=1}return result},proxy.ownKeys___=function(){var
i,keys,len,name,names,result,seen;if(this!==proxy)throw new TypeError('Inheritance from proxies not implemented yet.');keys=handler.getOwnPropertyNames_v___?handler.getOwnPropertyNames:handler.v___('getOwnPropertyNames'),names=keys.f___(handler,[]),result=[],len=names.length,seen={};for(i=0;i<len;++i){name=''+names[i],assertValidPropertyName(name);if(seen[name])continue;result.push(name),seen[name]=1}return result},proxy.allKeys___=function(){var
i,keys,len,name,names,result,seen;if(this!==proxy)throw new TypeError('Inheritance from proxies not implemented yet.');keys=handler.getPropertyNames_v___?handler.getPropertyNames:handler.v___('getPropertyNames'),names=keys.f___(handler,[]),result=[],len=names.length,seen={};for(i=0;i<len;++i){name=''+names[i],assertValidPropertyName(name);if(seen[name])continue;result.push(''+name),seen[name]=1}return result};function
fix(){var constructTrap,desc,descMap,fixer,i,isSafeFunc,keys,len;if(this!==proxy)throw new
TypeError('Inheritance from proxies not implemented yet.');if(proxy.fixing___)throw new
TypeError('Recursive fixing prohibited.');descMap=void 0;try{proxy.fixing___=true,fixer=handler.fix_v___?handler.fix:handler.v___('fix'),descMap=fixer.f___(handler,[])}finally{delete
proxy.fixing___}if(!descMap)throw new TypeError('Unable to fix the proxy.');isSafeFunc=isFunction(proxy)&&proxy.ok___,constructTrap=proxy.new___;for(i
in proxy)proxy.hasOwnProperty(i)&&delete proxy[i];isSafeFunc&&(markFunc(proxy),proxy.new___=constructTrap),keys=descMap.keys___(),len=keys.length;for(i=0;i<len;++i)if(isNumericName(keys[i])){desc=ToPropertyDescriptor(descMap.v___(keys[i]));if(!IsDataDescriptor(desc)||!desc.writable||!desc.configurable||!desc.enumerable)throw new
TypeError('Numeric properties returned from a fix trap must be writable, enumerable, configurable data properties.');proxy[keys[i]]=desc.value}else
proxy.DefineOwnProperty___(keys[i],descMap.v___(keys[i]))}proxy.freeze___=function(){return fix.call(this),this.freeze___()},proxy.pe___=function(){return fix.call(this),this.pe___()},proxy.seal___=function(){return fix.call(this),this.seal___()},proxy.DefineOwnProperty___=function(P,desc){var
extDesc;if(this!==proxy)throw new TypeError('Inheritance from proxies not implemented yet.');return P=''+P,extDesc=desc?FromPropertyDescriptor(desc):void
0,handler.defineProperty_m___?handler.defineProperty(P,extDesc):handler.m___('defineProperty',[P,extDesc])},proxy.GetOwnProperty___=function(P){var
desc,intDesc;if(this!==proxy)throw new TypeError('Inheritance from proxies not implemented yet.');P=''+P,desc=handler.getOwnPropertyDescriptor_m___?handler.getOwnPropertyDescriptor(P):handler.m___('getOwnPropertyDescriptor',[P]),intDesc=desc?ToPropertyDescriptor(desc):void
0;if(intDesc&&!intDesc.configurable)throw new TypeError('Proxy properties must be configurable.');return intDesc},proxy.HasProperty___=function(P){var
has;if(this!==proxy)throw new TypeError('Inheritance from proxies not implemented yet.');return P=''+P,has=handler.has_v___?handler.has:handler.v___('has'),isFunction(has)?!!has.f___(handler,[P]):defaultDerivedTraps.has.apply(handler,[P])},proxy.HasOwnProperty___=function(P){var
hasOwn;if(this!==proxy)throw new TypeError('Inheritance from proxies not implemented yet.');return P=''+P,hasOwn=handler.hasOwn_v___?handler.hasOwn:handler.v___('hasOwn'),isFunction(hasOwn)?!!hasOwn.f___(handler,[P]):defaultDerivedTraps.hasOwn.apply(handler,[P])}}CajaProxy={},CajaProxy.DefineOwnProperty___('create',{'value':markConstFunc(function
CajaProxy_create(handler,proto){var P,i,m,p,proxy;Type(handler)!=='Object'&&notObject(handler,'handler'),proxy=void
0;if(proto===void 0||proxy===null)proxy={};else{Type(proto)!=='Object'&&notObject(proto,'proto');if(proto.proxy___)throw new
TypeError('Proxies cannot inherit from proxies.');p=proto;while(p!==p.baseProto___){if(p.ne___!==p)throw new
TypeError('Proxies cannot inherit from extensible objects.');p=stdGetPrototypeOf(p)}proxy=beget(proto);for(i
in proto){m=endsWith_v___.test(i);if(!m)continue;P=m[1],proxy[P+'_v___']=false,proxy[P+'_w___']=false,proxy[P+'_gw___']=false,proxy[P+'_c___']=false,proxy[P+'_e___']=false,proxy[P+'_m___']=false,proxy[P+'_g___']=void
0,proxy[P+'_s___']=void 0,proxy[P+'_av___']=false}}return prepareProxy(proxy,handler),proxy}),'enumerable':true}),CajaProxy.DefineOwnProperty___('createFunction',{'value':markConstFunc(function(handler,callTrap,constructTrap){var
P,i,m,proto,proxy;Type(handler)!=='Object'&&notObject(handler,'handler'),isFunction(callTrap)||notFunction(callTrap,'callTrap'),constructTrap===void
0&&(constructTrap=function(){return new callTrap}),isFunction(constructTrap)||notFunction(constructTrap,'constructTrap'),proto=Function.prototype;if(proto.ne___!==proto)throw new
TypeError('Function.prototype must not be extensible to create function proxies.');proxy=markFunc(function(var_args){return callTrap.f___(safeDis(this),arguments)}),proxy.v___('length');for(i
in proto){m=endsWith_v___.test(i);if(!m)continue;P=m[1],proxy[P+'_v___']=false,proxy[P+'_w___']=false,proxy[P+'_gw___']=false,proxy[P+'_c___']=false,proxy[P+'_e___']=false,proxy[P+'_m___']=false,proxy[P+'_g___']=void
0,proxy[P+'_s___']=void 0,proxy[P+'_av___']=false}return prepareProxy(proxy,handler),proxy.new___=function(var_args){return constructTrap.apply(cajaVM.USELESS,arguments)},constructTrap&&(proxy.prototype=constructTrap.prototype),proxy}),'enumerable':true});function
getNewModuleHandler(){return myNewModuleHandler}function setNewModuleHandler(newModuleHandler){myNewModuleHandler=newModuleHandler}obtainNewModule=snowWhite({'handle':markConstFunc(function
handleOnly(newModule){return newModule})});function registerClosureInspector(module){this&&this.CLOSURE_INSPECTOR___&&this.CLOSURE_INSPECTOR___.supportsCajaDebugging&&this.CLOSURE_INSPECTOR___.registerCajaModule(module)}function
copy(obj){var result=Array.isArray(obj)?[]:{},keys=obj.ownKeys___(),len=keys.length,i,k,v;for(i=0;i<len;++i)k=keys[i],v=obj[k],isNumericName(k)?(result[k]=v):result.DefineOwnProperty___(k,{'value':v,'writable':true,'enumerable':true,'configurable':true});return result}function
makeNormalNewModuleHandler(){var imports=void 0,lastOutcome=void 0;function getImports(){return imports||(imports=copy(sharedImports)),imports}return snowWhite({'getImports':markConstFunc(getImports),'setImports':markConstFunc(function
setImports(newImports){imports=newImports}),'getLastOutcome':markConstFunc(function
getLastOutcome(){return lastOutcome}),'getLastValue':markConstFunc(function getLastValue(){return lastOutcome&&lastOutcome[0]?lastOutcome[1]:void
0}),'handle':markConstFunc(function handle(newModule){var outcome,result;registerClosureInspector(newModule),outcome=void
0;try{result=newModule.instantiate(___,getImports()),result!==NO_RESULT&&(outcome=[true,result])}catch(ex){outcome=[false,ex]}lastOutcome=outcome;if(outcome){if(outcome[0])return outcome[1];throw log(outcome[1]),outcome[1].stack&&log(outcome[1].stack),outcome[1]}return}),'handleUncaughtException':markConstFunc(function
handleUncaughtException(exception,onerror,source,lineNum){var message,shouldReport;lastOutcome=[false,exception],message=exception,'object'===typeof
exception&&exception!==null&&(message=''+(exception.message||exception.desc||exception.description||message)),isFunction(onerror)||notFunction(onerror,'onerror'),shouldReport=onerror.i___(message,''+source,''+lineNum),shouldReport!==false&&log(source+':'+lineNum+': '+message)})})}function
isFlag(name){return/_v___$/.test(name)||/_w___$/.test(name)||/_gw___$/.test(name)||/_c___$/.test(name)||/_e___$/.test(name)||/_g___$/.test(name)||/_s___$/.test(name)||/_m___$/.test(name)||/_av___$/.test(name)}function
copyToImports(imports,source){var p;for(p in source)source.hasOwnProperty(p)&&(/__$/.test(p)?isFlag(p)||(imports[p]=source[p]):isNumericName(p)?(imports[p]=source[p]):imports.DefineOwnProperty___(p,{'value':source[p],'writable':true,'enumerable':true,'configurable':true}))}function
prepareModule(module,load){var i,majorCajaVersion,majorWinVersion,message,props;if(cajaBuildVersion!==module.cajolerVersion){message='Version error: es53 expects '+cajaBuildVersion+' but module is '+module.cajolerVersion,majorCajaVersion=(String(cajaBuildVersion).split(/[mM]/))[0],majorWinVersion=(String(module.cajolerVersion).split(/[mM]/))[0];if(majorCajaVersion===majorWinVersion)message+='  Continuing because major versions match.',log(message);else
throw new TypeError(message)}registerClosureInspector(module);function theModule(extraImports){var
imports=copy(sharedImports);return copyToImports({'load':load,'cajaVM':cajaVM}),copyToImports(imports,extraImports),module.instantiate(___,imports)}props=['cajolerName','cajolerVersion','cajoledDate','moduleURL'];for(i=0;i<props.length;++i)theModule.DefineOwnProperty___(props[i],{'value':module[props[i]],'writable':false,'enumerable':true,'configurable':false});return!module.includedModules||theModule.DefineOwnProperty___('includedModules',{'value':freeze(module.includedModules),'writable':false,'enumerable':true,'configurable':false}),theModule.instantiate___=function(___,IMPORTS___){return module.instantiate(___,IMPORTS___)},markConstFunc(theModule)}function
loadModule(module){return freeze(module),markConstFunc(module.instantiate),myNewModuleHandler.m___('handle',[module])}function
grantFunc(obj,name){obj.DefineOwnProperty___(name,{'value':markConstFunc(obj[name]),'writable':false,'enumerable':false,'configurable':false})}function
grantRead(obj,name){obj.DefineOwnProperty___(name,{'value':obj[name],'writable':false,'enumerable':false,'configurable':false})}function
grantTypedMethod(proto,name){var f,original;name=''+name,original=proto[name],f=function(){},f.prototype=proto,proto.DefineOwnProperty___(name,{'value':markFunc(function
guardedApplier(var_args){if(!(this instanceof f))throw new TypeError('Tamed method applied to the wrong class of object.');return original.apply(this,arguments)}),'enumerable':false,'configurable':true,'writable':true})}function
grantInnocentMethod(proto,name){var original=proto[name];proto.DefineOwnProperty___(name,{'enumerable':false,'configurable':false,'get':markFunc(function(){return function
guardedApplier(var_args){var feralThis=safeDis(taming.untame(this)),feralArgs=taming.untame(slice.call(arguments,0)),feralResult=original.apply(feralThis,feralArgs);return taming.tame(feralResult)}}),'set':void
0})}function all2(func2,arg1,arg2s){var len=arg2s.length,i;for(i=0;i<len;i+=1)func2(arg1,arg2s[i])}function
useGetHandler(obj,name,getHandler){var desc;getHandler=markFunc(getHandler),name=''+name,desc=obj.GetOwnProperty___(name),!desc||!IsAccessorDescriptor(desc)?(desc={'enumerable':false,'configurable':true,'get':getHandler,'set':void
0}):(desc.get=getHandler),obj.DefineOwnProperty___(name,desc)}function useSetHandler(obj,name,setHandler){var
desc;setHandler=markFunc(setHandler),name=''+name,desc=obj.GetOwnProperty___(name),IsAccessorDescriptor(desc)?(desc.set=setHandler):(desc={'enumerable':false,'configurable':true,'get':void
0,'set':setHandler}),obj.DefineOwnProperty___(name,desc)}function hasOwnProp(obj,name){return obj&&obj.hasOwnProperty(name)}cajaVM=whitelistAll({'log':log,'enforce':enforce,'enforceType':enforceType,'enforceNat':enforceNat,'Nat':enforceNat,'Token':Token,'identity':identity,'callWithEjector':callWithEjector,'eject':eject,'GuardT':GuardT,'Trademark':Trademark,'guard':guard,'passesGuard':passesGuard,'stamp':stamp,'makeTableGuard':makeTableGuard,'makeSealerUnsealerPair':makeSealerUnsealerPair,'tamperProof':freeze,'constFunc':constFunc,'def':def,'is':SameValue,'makeArrayLike':makeArrayLike,'isFunction':isFunction,'USELESS':USELESS,'manifest':manifest,'allKeys':allKeys});function
readImport(imports,name){name=''+name;if(imports.HasProperty___(name))return imports.v___(name);throw new
ReferenceError(('\"'+name+'\" is not defined in this scope.'))}function declareImport(imports,name){if(imports.HasProperty___(name))return;imports.w___(name,void
0)}function writeImport(imports,name,value){if(imports.HasProperty___(name))return imports.w___(name,value),value;throw new
ReferenceError(('\"'+name+'\" is not defined in this scope.'))}function goodParseInt(n,radix){var
isHexOrOctal,isOct;return n=''+n,radix=+radix,isHexOrOctal=/^\s*[+-]?\s*0(x?)/.exec(n),isOct=isHexOrOctal?isHexOrOctal[1]!=='x':false,isOct&&(radix!==radix||0===radix)?parseInt(n,10):parseInt(n,radix)}sharedImports=snowWhite({'cajaVM':cajaVM,'null':null,'false':false,'true':true,'NaN':NaN,'Infinity':Infinity,'undefined':void
0,'parseInt':markFunc(goodParseInt),'parseFloat':markFunc(parseFloat),'isNaN':markFunc(isNaN),'isFinite':markFunc(isFinite),'decodeURI':markFunc(decodeURI),'decodeURIComponent':markFunc(decodeURIComponent),'encodeURI':markFunc(encodeURI),'encodeURIComponent':markFunc(encodeURIComponent),'escape':escape?markFunc(escape):void
0,'Math':Math,'JSON':safeJSON,'Object':Object,'Array':Array,'String':String,'Boolean':Boolean,'Number':Number,'Date':Date,'RegExp':RegExp,'Function':FakeFunction,'Proxy':CajaProxy,'Error':Error,'EvalError':EvalError,'RangeError':RangeError,'ReferenceError':ReferenceError,'SyntaxError':SyntaxError,'TypeError':TypeError,'URIError':URIError,'WeakMap':WeakMap}),cajaVM.DefineOwnProperty___('sharedImports',{'enumerable':true,'configurable':true,'writable':true,'value':sharedImports}),Object.prototype.m___=function(name,as){var
m,ownerObj;return name=''+name,this[name+'_m___']?this[name].f___(this,as):(m=this.v___(name),typeof
m!=='function'&&notFunction(m,'property \"'+name+'\"'),ownerObj=this[name+'_v___'],ownerObj&&ownerObj!==Function.prototype&&fastpathMethod(ownerObj,name),m.f___(this,as))},___={'sharedImports':sharedImports,'USELESS':USELESS,'args':args,'deodorize':deodorize,'copy':copy,'i':isIn,'iM':initializeMap,'f':markSafeFunc,'markFunc':markFunc,'Trademark':Trademark,'makeSealerUnsealerPair':makeSealerUnsealerPair,'getId':getId,'getImports':getImports,'unregister':unregister,'newTable':newTable,'whitelistAll':whitelistAll,'snowWhite':snowWhite,'markConstFunc':markConstFunc,'makeDefensibleFunction':makeDefensibleFunction,'makeDefensibleObject':makeDefensibleObject,'ri':readImport,'di':declareImport,'wi':writeImport,'copyToImports':copyToImports,'grantRead':grantRead,'grantFunc':grantFunc,'grantTypedMethod':grantTypedMethod,'grantInnocentMethod':grantInnocentMethod,'all2':all2,'hasOwnProp':hasOwnProp,'markCtor':function(fn){return freeze(markFunc(fn)),fn},'useGetHandler':useGetHandler,'useSetHandler':useSetHandler,'primFreeze':snowWhite,'isJSONContainer':isExtensible,'getLogFunc':getLogFunc,'setLogFunc':setLogFunc,'callPub':function(obj,name,args){return obj.m___(name,args)},'readPub':function(obj,name){return obj.v___(name)},'canRead':function(obj,name){return name+'_v___'in
obj},'freeze':freeze,'getNewModuleHandler':getNewModuleHandler,'setNewModuleHandler':setNewModuleHandler,'obtainNewModule':obtainNewModule,'makeNormalNewModuleHandler':makeNormalNewModuleHandler,'prepareModule':prepareModule,'loadModule':loadModule,'NO_RESULT':NO_RESULT,'def':def,'isDefinedInCajaFrame':isDefinedInCajaFrame,'rawDelete':rawDelete,'getter':getter,'setter':setter,'directConstructor':directConstructor,'BASE_OBJECT_CONSTRUCTOR':BASE_OBJECT_CONSTRUCTOR,'DISABLE_SECURITY_FOR_DEBUGGER':false},cajaVMKeys=ownEnumKeys(cajaVM);for(i=0;i<cajaVMKeys.length;++i)___[cajaVMKeys[i]]=cajaVM[cajaVMKeys[i]];setNewModuleHandler(makeNormalNewModuleHandler())})(this),typeof
window!=='undefined'&&(window['___']=___,window['safeJSON']=safeJSON,window['WeakMap']=WeakMap,window['cajaVM']=cajaVM),(function(){var
enqueue;function reject(reason){function rejected(op,arg1,arg2,arg3){return undefined===op?rejected:'WHEN'===op?(arg2||reject)(reason):arg1?arg1(reject(reason)):reject(reason)}return rejected.reason=reason,rejected.isPromise___=true,rejected}function
ref(value){if(null===value||undefined===value)return reject({'class':['NaO']});if('number'===typeof
value&&!isFinite(value))return reject({'class':['NaN']});function fulfilled(op,arg1,arg2,arg3){var
r;if(undefined===op)return value;switch(op){case'WHEN':r=value;break;case'GET':undefined===arg2||null===arg2?(r=value):(r=value[arg2]);break;case'POST':undefined===arg2||null===arg2?(r=reject({})):(r=value[arg2].apply(value,arg3));break;case'PUT':undefined===arg2||null===arg2?(r=reject({})):(value[arg2]=arg3,r={});break;case'DELETE':undefined===arg2||null===arg2?(r=reject({})):(delete
value[arg2],r={});break;default:r=reject({})}return arg1?arg1.apply(null,[r]):r}return fulfilled.isPromise___=true,fulfilled}enqueue=(function(){var
active=false,pending=[],run=function(){var task=pending.shift();0===pending.length?(active=false):setTimeout(run,0),task()};return function(task){pending.push(task),active||(setTimeout(run,0),active=true)}})();function
forward(p,op,arg1,arg2,arg3){enqueue(function(){p(op,arg1,arg2,arg3)})}function
promised(value){return'function'===typeof value&&value.isPromise___===true?value:ref(value)}function
defer(){var pending=[],value;function promise(op,arg1,arg2,arg3){if(undefined===op)return pending?promise:value();pending?pending.push({'op':op,'arg1':arg1,'arg2':arg2,'arg3':arg3}):forward(value,op,arg1,arg2,arg3)}return promise.isPromise___=true,___.primFreeze({'promise':___.markConstFunc(promise),'resolve':___.markConstFunc(function(p){var
i,todo,x;if(!pending)return;todo=pending,pending=null,value=promised(p);for(i=0;i!==todo.length;i+=1)x=todo[+i],forward(value,x.op,x.arg1,x.arg2,x.arg3)})})}Q={'run':___.markConstFunc(enqueue),'reject':___.markConstFunc(reject),'ref':___.markConstFunc(ref),'defer':___.markConstFunc(defer),'near':___.markConstFunc(function(value){return'function'===typeof
value&&value.isPromise___===true?value():value}),'when':___.markConstFunc(function(value,fulfilled,rejected){var
r=defer(),done=false;return forward(promised(value),'WHEN',function(x){if(done)throw new
Error;done=true,r.resolve(ref(x)('WHEN',fulfilled,rejected))},function(reason){if(done)throw new
Error;done=true,r.resolve(rejected?rejected.apply(null,[reason]):reject(reason))}),r.promise}),'get':___.markConstFunc(function(target,noun){var
r=defer();return forward(promised(target),'GET',r.resolve,noun),r.promise}),'post':___.markConstFunc(function(target,verb,argv){var
r=defer();return forward(promised(target),'POST',r.resolve,verb,argv),r.promise}),'put':___.markConstFunc(function(target,noun,value){var
r=defer();return forward(promised(target),'PUT',r.resolve,noun,value),r.promise}),'remove':___.markConstFunc(function(target,noun){var
r=defer();return forward(promised(target),'DELETE',r.resolve,noun),r.promise})},___.primFreeze(Q)})(),typeof
window!=='undefined'&&(window['Q']=Q),prepareModuleFromText___=function(moduleText){var
rawModule=undefined;return(function(){var ___={'loadModule':function(m){rawModule=m}};eval(moduleText)})(),___.prepareModule(rawModule,undefined)},typeof
window!=='undefined'&&(window['prepareModuleFromText___']=prepareModuleFromText___),loadModuleMaker=function(rootUrl,cajolingServiceClient,uriUtils){var
moduleCache={},evalModuleObjFromJson=function(moduleJson){var moduleObj=undefined;return(function(){var
___={'loadModule':function(m){moduleObj=m}};eval(moduleJson.js)})(),moduleObj},resolveDependencies=function(moduleObj,loadForThisModule){var
result=Q.defer(),count,i,size;if(moduleObj.includedModules!==undefined&&moduleObj.includedModules.length!==0){size=moduleObj.includedModules.length,count=0;for(i=0;i<size;++i)Q.when(loadForThisModule.async(moduleObj.includedModules[i]),function(childModule){++count,count===size&&result.resolve(true)},function(err){result.resolve(Q.reject(err))})}else
result.resolve(true);return result.promise},makeLoad=function(baseUrl){var load=function(url){var
fullUrl=uriUtils.resolve(baseUrl,url);if(moduleCache['$'+fullUrl]||Q.near(moduleCache['$'+fullUrl]).isPromise___)throw new
Error(('The static module '+fullUrl+' cannot be resolved.'));return Q.near(moduleCache['$'+fullUrl])},evalAndResolveFromJson=function(url,moduleJson){var
result=Q.defer(),loadForThisModule=makeLoad(url),moduleObj=evalModuleObjFromJson(moduleJson);return Q.when(resolveDependencies(moduleObj,loadForThisModule),function(_){try{result.resolve(___.prepareModule(moduleObj,loadForThisModule))}catch(ex){result.resolve(Q.reject(ex))}},function(ex){result.resolve(Q.reject(ex))}),result.promise()},loadCajoledJson___=function(url,moduleJson){var
moduleDeferred;if(moduleCache['$'+url])throw new Error(('Module already loaded: '+url));return moduleDeferred=Q.defer(),Q.when(evalAndResolveFromJson(url,moduleJson),function(module){moduleDeferred.resolve(module)},function(ex){moduleDeferred.resolve(Q.reject(ex))}),moduleCache['$'+url]=moduleDeferred.promise,moduleDeferred.promise},async=function(url,contentType){var
fullUrl=uriUtils.resolve(baseUrl,url),mimeType,moduleDeferred;return moduleCache['$'+fullUrl]?moduleCache['$'+fullUrl]:(moduleDeferred=Q.defer(),mimeType=contentType||uriUtils.mimeTypeOf(url),Q.when(cajolingServiceClient.cajoleUrl(fullUrl,mimeType),function(moduleJson){Q.when(evalAndResolveFromJson(fullUrl,moduleJson),function(module){moduleDeferred.resolve(module)},function(ex){moduleDeferred.resolve(Q.reject(ex))})},function(ex){moduleDeferred.resolve(Q.reject(ex))}),moduleCache['$'+fullUrl]=moduleDeferred.promise,moduleDeferred.promise)},asyncAll=function(moduleUrls,contentType){var
result=Q.defer(),modulePromises=[],modules={},i,waitNext;for(i=0;i<moduleUrls.length;++i)modulePromises[i]=async(moduleUrls[i],contentType);return waitNext=function(idx){idx===moduleNames.length?result.resolve(modules):Q.when(modulePromises[idx],function(theModule){modules[moduleNames[idx]]=theModule,waitNext(idx+1)},function(reason){result.resolve(Q.reject(reason))})},waitNext(0),result.promise};return load.DefineOwnProperty___('async',{'value':___.markConstFunc(async),'writable':false,'enumerable':true,'configurable':false}),load.DefineOwnProperty___('asyncAll',{'value':___.markConstFunc(asyncAll),'writable':false,'enumerable':true,'configurable':false}),load.loadCajoledJson___=loadCajoledJson___,___.markConstFunc(load)};return makeLoad(rootUrl)},typeof
window!=='undefined'&&(window['loadModuleMaker']=loadModuleMaker),cajaIframeDone___()}